src/App.vue, src/components/AddPeopleAndRoles/ListPeopleAndRoles.vue, src/components/IncorporationAgreement/AgreementType.vue, src/utils/auth-helper.ts, src/views/Alteration.vue, src/views/Correction.vue, src/views/DefineCompany.vue, src/views/auth/Signin.vue
*Issue #:* /bcgov/entity#4553
- added appReady to let views know when they can load data
- added profileReady so Signin can let App know when user is authed
- added haveData so views can let App know when to hide spinner
- added haveChanges so views can let App know whether to show Fee Summary
- simplified App create since it can be called without authentication
- created onProfileReady to load one-time app data
- updated initApp to load repeatable app data
- deleted unneeded onRouteChanged (now using events instea of route
change to init app)
- cleared haveChanges after view loading (cleaner than ignoring changes)
- updated views to load data in onAppReady and emit haveData when done
- updated Signin view to emit profileReady when authed
By submitting this pull …
=> more framework updates for proper loading and reloading

src/App.vue, src/components/YourCompany/CompanyName/CorrectNameRequest.vue, src/mixins/name-request-mixin.ts
*Issue #:* /bcgov/entity#5125
*Description of problems:*
- we want the components under the dialog to still be displayed (albeit grayed out)
- if we failed to change the NR, the form should display if we try again
- don't un-render `<main>` on NR error
- minor cleanup
=> correction NR fix

src/components/PeopleAndRoles/PeopleAndRoles.vue, src/components/YourCompany/OfficeAddresses.vue, src/mixins/common-mixin.ts
*Issue #:* /bcgov/entity#5076
- scrolled to top after office addresses edit/cancel
- moved method to common mixin
=> added "scroll to top" to OfficeAddresses

src/components/PeopleAndRoles/ListPeopleAndRoles.vue, src/components/PeopleAndRoles/OrgPerson.vue, src/components/PeopleAndRoles/PeopleAndRoles.vue, src/components/dialogs/ConfirmDialog.vue, src/mixins/common-mixin.ts, tests/unit/ListPeopleAndRoles.spec.ts, tests/unit/OrgPerson.spec.ts, tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#5191
Commit 1:
- removed locked roles for a person
- always enable Done button
- validate forms when Done is clicked
Commit 2:
- created common method to format an officer's full name
- prompt user on Undo for confirmation to revert CP
- added "no missing roles" condition to component validity computation
- misc cleanup
Commit 3:
- added "attach" prop to confirm dialog
=> fixed misc People And Roles bugs

src/components/PeopleAndRoles/ListPeopleAndRoles.vue, src/components/YourCompany/OfficeAddresses.vue
*Issue #:* /bcgov/entity#5368
This commit fixes the People & Roles and Office Addresses components. Other components will need to be fixed in future tickets/commits.
- fixed action buttons vertical layout
- toggle more actions menu-down/up icon
- fixed more actions items layout
- fixed more actions items colour
- attached v-menu to prevent "flying in" on undo
=> misc layout fixes

public/index.html, src/components/PeopleAndRoles/PeopleAndRoles.vue, src/components/YourCompany/OfficeAddresses.vue, src/interfaces/stepper-interfaces/YourCompany/address-interface.ts, src/mixins/common-mixin.ts, tests/unit/OfficeAddresses.spec.ts
*Issue #:* /bcgov/entity#5420
- closed v-menu on button clicks
- ignore Address Country Description in direct comparisons
- ignore Address Type in mailing/delivery comparisons
- set address types on assignments
- added optional addressType property to interface
- updated isSame() to handle array of omitted props
- updated a unit test
- also removed unneeded font preload
=> fixed address comparisons and assignments

src/components/IncorporationAgreement/AgreementType.vue, src/components/PeopleAndRoles/PeopleAndRoles.vue, src/components/ShareStructure/ShareStructure.vue, src/components/YourCompany/NameTranslations/NameTranslation.vue, src/components/YourCompany/OfficeAddresses.vue, src/components/YourCompany/YourCompany.vue, src/components/common/Actions.vue, src/store/actions/actions-model.ts, src/store/getters/state-getters.ts, src/store/mutations/mutations-model.ts, tests/unit/Actions.spec.ts, tests/unit/state-getters.spec.ts
*Issue #:* /bcgov/entity#5115
Commit 1:
- don't show buttons until Entity Type is known
- added missing setter (action)
- deleted unused getter
- updated Actions unit tests
Commit 2:
- set editing flag when Incorporation Agreement form is rendered
- set editing flag when People and Roles add/edit form is rendered
- set editing flag when Share Structure add/edit is in progress
- set editing flag when Office Addresses is in editing mode
- set editing flag when Company Name is in editing mode
- set editing flag when Name Translations is in editing mode
- renamed some actions and mutations for consistency
- updated unit tests due to renames
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
=> disable buttons when editing

.github/workflows/cd.yml, codecov.yaml
*Issue #:* /bcgov/entity#5626
1. Update for deprecating set-env command of GHA.
2. Expand the range of codecov check to 50% - 100%.
=> Update for set environment variables issue of GHA.

package-lock.json, package.json, src/components/Summary/AlterationSummary.vue, src/components/YourCompany/NameTranslations/AddNameTranslation.vue, src/components/YourCompany/NameTranslations/NameTranslation.vue, tests/unit/AlterationSummary.spec.ts
*Issue #:* /bcgov/entity#5176
- repurpose name translation component to show on summary page
- ensure translations are in upper case on summary page
- add test
=> 5176 - show name translations on summary page

Makefile, package-lock.json, package.json
- updated cli-plugin-eslint package to get "no-fix" fix
- added npm script for lint:nofix
- updated Makefile to run lint:nofix (ie, to fail on errors)
CI script says:
```
DONE  All lint errors auto-fixed.
```
CD script says:
```
error: Trailing spaces not allowed (no-trailing-spaces) at src/components/Summary/DocumentsDelivery.vue:4:75:
2 |   <div class="ma-6 pb-6" id="document-delivery-section" :class="{ 'invalid': documentDeliveryInvalid }">
3 |     <h2>1. Alteration Documents Delivery</h2>
> 4 |     <div class="pt-4 pb-4">Copies of the alteration documents will be sent 
|                                                                           ^
5 |       to the following email address listed below.</div>
6 |     <v-card flat class="pt-4 …
```
=> Updated CI make to fail on lint errors

package-lock.json, package.json, src/components/Summary/AlterationSummary.vue, src/components/YourCompany/NameTranslations/NameTranslation.vue, tests/unit/AlterationSummary.spec.ts
*Issue #:* /bcgov/entity#5176
- was showing blank section with line before
- also, don't show "changed" chip on summary page
=> only show section if name translations has changed

src/App.vue
- per Tracey, don't have the Fee Summary overlap the other content on narrow screens
- better responsiveness (mobile) is future work
=> Disabled main column wrapping

package-lock.json, package.json, src/components/PeopleAndRoles/OrgPerson.vue, src/components/YourCompany/NameTranslations/AddNameTranslation.vue, src/components/common/EffectiveDateTime.vue, src/interfaces/utils-interfaces/form-field-type.ts, src/interfaces/utils-interfaces/form-type.ts, tests/unit/EffectiveDateTime.spec.ts
*Issue #:* /bcgov/entity#6724
- Changed EffectiveDateTime to enable all the fields when selecting FED;
- Updated tests
**This PR is part of 6724 regarding the checkbox: "Can we have the users able to select date/time/am in any order or is there a reason we force users to select the date field first? Would prefer all the fields are "active" when you click the FED radio button"**
=> 6724 - EffectiveDateTime to enable all the fields when selecting FED

src/components/YourCompany/FolioInformation.vue, src/components/YourCompany/FolioNumber.vue, src/components/YourCompany/YourCompany.vue, tests/unit/FolioInformation.spec.ts
*Issue #:* /bcgov/entity#5024
- show FN for premium accounts only
- hide FN actions in a correction filing
- hide FN actions from staff users
Note that I'm not updating the app version so that: I don't conflict with Andre's PR, and because this build is close enough to other builds today.
=> Show Folio Number with conditional actions

package-lock.json, package.json, src/components/YourCompany/OfficeAddresses.vue, src/mixins/filing-template-mixin.ts, tests/unit/OfficeAddresses.spec.ts
*Issue #:* /bcgov/entity#7416
* Include Staff payment in filing and draft parsing.
* Added Staff payment to alteration filing build.
* Created method to parse staff payment into store for both alterations and corrections.
* Fixed Office addresses bug where it wouldn't initialize the data after changing views, would only update the component when the Store values changed, which only happened once in Alterations.
* verified resolution dates are working as expected.
* Minor unit test updates to include the additional event.
=> Staff Payment and Office Address Bugs

package-lock.json, package.json, src/mixins/filing-template-mixin.ts
*Issue #:* /bcgov/entity#5024
- the Folio Number needs to be restored when parsing a draft alteration
- as this is a functional change, the app version was updated
=> BUGFIX: restore Folio Number when parsing draft alteration

package-lock.json, package.json, src/App.vue
*Issue #:* /bcgov/entity#10999
This is not truly a bug since the code works, but it works due to lucky timing. This change -- same as in Create UI -- ensures that create() is run before onRouteChange() runs. This ensures that the current date is set before anything else that might depend on it runs.
- renamed initApp -> fetchData (same as Create UI)
- init app at end of create(), not on initial route change
- app version = 0.6.30
=> 10999 Fixed init bug

package-lock.json, package.json, src/components/common/dialogs/PaymentErrorDialog.vue, src/components/common/dialogs/StaffPaymentErrorDialog.vue, tests/unit/PaymentErrorDialog.spec.ts
Issue #: [/bcgov/entity#9014](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/9014)
Description of changes:
When a payment error occurred, a popup window for "Unable to process payment" show up.
tags are included in the text in the popup window, and they need to be removed.
=> 9014 HTML tags show up in the warning popup window

package-lock.json, package.json, src/assets/styles/base.scss, src/components/Alteration/ChangeSummary.vue, src/components/common/HelpSection.vue, src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue, src/components/common/PeopleAndRoles/OrgPerson.vue, src/components/common/PeopleAndRoles/PeopleAndRoles.vue, src/resources/Change/GeneralPartnershipResource.ts, src/resources/Change/SoleProprietorshipResource.ts, src/store/getters/state-getters.ts
*Issue #:* [bcgov/entity/11932](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/11932)
_UXA 1 of 4 - Reviewed in DEV / BCREG0017 using: TRACEY'S SP DBA TEST BUSINESS_
**Sole Prop (Person):**
**Edit View:**
**Table View:**
_UXA 2 of 4 - Reviewed in DEV / BCREG0017 using: TRACEY'S SP DBA TEST BUSINESS_
**DBA - Sole Prop (Business):**
**Edit View:**
**Table View:**
_UXA 3 of 4 - Reviewed in DEV / BCREG0017 using: TRACEY'S TEST GP BUSINESS_
**GP Flow:**
**Validation for less than 2 Partners:**
**Edit Partner View:**
**Add Business Partner - Business or Corporation Unregistered in B.C. intro text:**
**Add Business Partner- Business or Corporation Look Up intro text:**
**Add Business Partner:**
Business Partner …
=> 11932 Proprietor and Partner - UX Improvements

package-lock.json, package.json, src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue, src/components/common/PeopleAndRoles/OrgPerson.vue, tests/unit/OrgPerson.spec.ts
Issue #: [bcgov/entity/11932](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/11932)
**SP with Individual Proprietor**
**GP**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-edit-ui license (Apache 2.0).
Added:
=> 11932 Fix Proprietor and Partner - UX Improvements

package-lock.json, package.json, src/components/Conversion/ConversionNOB.vue, src/components/common/PeopleAndRoles/OrgPerson.vue, src/resources/Conversion/SoleProprietorshipResource.ts, src/store/actions/actions-model.ts, tests/unit/ConversionNatureOfBusiness.spec.ts
*Issue #:* /bcgov/entity#12419
- removed name change confirmation checkbox in conversion filing
- added check for required NAICS description
- don't revert NAICS on cancel
- use NAICS value when computing validity
- app version = 3.1.11
- removed help section from SP conversion
=> 12419 Removed name change checkbox + some NAICS fixes

package-lock.json, package.json, src/interfaces/resource-interfaces/resource-interface.ts, src/resources/Alteration/BenefitCompanyResource.ts, src/resources/Alteration/CooperativeResource.ts, src/resources/Change/GeneralPartnershipResource.ts, src/resources/Change/SoleProprietorshipResource.ts, src/resources/Conversion/GeneralPartnershipResource.ts, src/resources/Conversion/SoleProprietorshipResource.ts, src/views/Conversion.vue
*Issue #:* /bcgov/[entity12427](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/12427)
- Removed staff payment component and associated methods from Conversion view.
- Updated ResourceIF to use FilingDataIF
- Hardcoded waive fees code to for a GP and SP conversion filing.
- Updated Alteration (BenefitCompanyResource, CooperativeResource), 
Change (GeneralPartnershipResource, SoleProprietorshipResource) and
Conversion (GeneralPartnershipRescource, SoleProprietorshipResource)
to use the updated ResourceIF.
- App version = 3.1.13
=> 12427 Removed staff payment component from conversion filing.

package-lock.json, package.json, src/components/common/CertifySection.vue, src/views/Change.vue
*Issue #:* /bcgov/entity#[12169](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/12169)
Commit 1:
- Updated bcrs-shared-components/certify version 1.0.18 => 2.0.4
- Removed CSS from certify common component as it is now covered by updated certify component
- Non-staff users now cannot edit the certify field, and it is prefilled based on the users login name
- App version = 3.1.14
Commit 2-3:
- Resolving merge conflicts
Commit 4:
- Removing code that I added that was unneeded
Commit 5-7:
- Applying requested fixes.
Test notes:
-Alteration, Change and Conversion filings all use the certify component
Tested locally that the changes were not applied to other views that use the CertifySection component, specifically …
=> 12169 Prefill Certify component for non-staff user. Updated certify component to latest version.

package-lock.json, package.json, src/components/common/YourCompany/BusinessContactInfo.vue, src/components/common/YourCompany/OfficeAddresses.vue, src/interfaces/stepper-interfaces/YourCompany/address-interfaces.ts, src/mixins/filing-template-mixin.ts
*Issue #:* /bcgov/entity#12419
- made BusinessContactInfo invalid when email is empty
- implemented workaround so office address "same as" is disabled when mailing address is not in BC, Canada
- added conditional chaining to avoid error when saving correction parties without actions
- removed empty contact point email workaround
- app version = 3.1.17
=> 12419 Make Business Contact Info email required + misc fixes

package-lock.json, package.json, src/resources/BreadCrumbResources.ts, src/utils/fetchConfig.ts, src/utils/navigate.ts, tests/unit/App.spec.ts
*Issue #:* [/bcgov/entity#12529](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/12529)
- get account id from CURRENT_ACCOUNT
- BreadCrumbResource.ts
- business-lookup.services.ts
- navigate.ts
- removed ACCOUNT_ID from fetchConfig.ts
=> 12529 Edit UI: get account id from CURRENT_ACCOUNT

package-lock.json, package.json, src/App.vue, src/components/Change/ChangeSummary.vue, src/components/Conversion/ConversionNOB.vue, src/components/Conversion/ConversionSummary.vue, src/components/common/Actions.vue, src/components/common/CertifySection.vue, src/components/common/EffectiveDateTime.vue, src/components/common/YourCompany/ChangeBusinessType.vue, src/components/common/YourCompany/CompanyName/CorrectNameRequest.vue, src/components/common/YourCompany/NatureOfBusiness.vue, src/components/common/YourCompany/OfficeAddresses.vue, src/components/common/YourCompany/SummaryDefineCompany.vue, src/components/common/YourCompany/YourCompany.vue, src/dialogs/FileAndPayInvalidNameRequestDialog.vue, src/interfaces/filing-interfaces/chg-registration-interfaces.ts, src/interfaces/filing-interfaces/conversion-interfaces.ts, src/interfaces/filing-interfaces/index.ts, src/interfaces/filing-interfaces/registration-filing-interface.ts, src/interfaces/filing-interfaces/special-resolution-filing-interface.ts, src/interfaces/store-interfaces/state-interfaces/correction-information-interface.ts, src/mixins/common-mixin.ts, src/mixins/filing-template-mixin.ts, src/services/legal-services.ts, src/store/getters/state-getters.ts, src/views/Correction/BenCorrection.vue, tests/unit/ConversionNOB.spec.ts, tests/unit/filing-template-mixin.spec.ts, tests/unit/state-getters.spec.ts
*Issue #:* /bcgov/entity#13059
- renamed hasNatureOfBusinessChanged to hasNaicsChanged
- add error bar to Records Office
- some NR cleanup
- some interface cleanup
- added undefined fallback to naicsCode in draft filings
- removed unnecessary destructuring in draft filings
- removed obsolete natureOfBusiness
- saved NR data in Conversion draft filings
- cloned entity snapshot to prevent object overlaps
- store business info when parsing Change and Conversion filings
- save and don't restore correction Completing Party
- added some filing template helpers
- added conditional chaining to some getters (and handling in components)
- fixed havePeopleAndRolesChanged
- fixed hasNatureOfBusinsesChanged
- fixed some typings
- fixed some schema errors
- …
=> 13059 Updated correction filing + misc fixes + cleanup

package-lock.json, package.json, src/components/common/Detail.vue, src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue, src/components/common/PeopleAndRoles/OrgPerson.vue, src/components/common/PeopleAndRoles/PeopleAndRoles.vue, src/components/common/YourCompany/OfficeAddresses.vue, src/components/common/YourCompany/StartDate.vue, src/components/common/YourCompany/YourCompany.vue, src/interfaces/filing-interfaces/correction-filing-interface.ts, src/mixins/filing-template-mixin.ts, src/store/getters/state-getters.ts, src/views/Alteration.vue, src/views/Change.vue, src/views/Conversion.vue, src/views/Correction/BenCorrection.vue, src/views/Correction/FmCorrection.vue, src/views/SpecialResolution.vue, tests/unit/Alteration.spec.ts, tests/unit/BenCorrection.spec.ts, tests/unit/Change.spec.ts, tests/unit/Conversion.spec.ts, tests/unit/FmCorrection.spec.ts, tests/unit/SpecialResolution.spec.ts, tests/unit/state-getters.spec.ts
*Issue #:* bcgov/entity#13192 and bcgov/entity#13334
Commit 1:
- deleted corrected filings from correction filing interface
- stop saving corrected incorporation application
- fixed missing prepareParties() for firm corrections
- set fallback correction type to CLIENT (more complete than STAFF, and staff can delete and recreate if wrong)
- renamed "business snapshot" -> "entity snapshot"
- app version = 3.5.25
Commit 2:
- renamed isBenIaCorrectionFiling -> isBenCorrectionFiling
- cleaned up Filing Template Mixin
Commit 3:
- fixed unit test errors
=> 13192 Clean up BEN IA correction to no longer save corrected IA object

package-lock.json, package.json, src/components/common/CourtOrderPoa.vue, src/interfaces/filing-interfaces/chg-registration-interfaces.ts, src/mixins/filing-template-mixin.ts, src/views/Alteration.vue, src/views/Change.vue, src/views/SpecialResolution.vue, tests/unit/CourtOrderPoa.spec.ts
*Issue #:* bcgov/entity#13193
- added missing getter to CourtOrderPoa component
- moved CSS from callers to CourtOrderPoa component
- fixed incorrect Court Order type in Change of Registration interface
- saved missing fields in Change of Registration filing object
- added fallbacks for missing restored fields
- restored missing fields from Change of Registration filing object
- used local CourtOrderPoa shim component for Alterations
- misc cleanup
- app version = 3.5.27
=> 13193 Added missing Change of Registration filing code + misc cleanup

package-lock.json, package.json, src/components/Alteration/Articles/CompanyProvisions.vue, src/components/Conversion/ConversionNOB.vue, src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue, src/components/common/YourCompany/BusinessStartDate.vue, src/components/common/YourCompany/NameTranslations/ListNameTranslation.vue, src/components/common/YourCompany/NameTranslations/NameTranslation.vue, src/components/common/YourCompany/NatureOfBusiness.vue, src/components/common/YourCompany/OfficeAddresses.vue, src/interfaces/filing-interfaces/chg-registration-interfaces.ts, src/interfaces/store-interfaces/state-interfaces/correction-information-interface.ts, src/mixins/filing-template-mixin.ts, src/store/getters/state-getters.ts, tests/unit/BusinessStartDate.spec.ts, tests/unit/OfficeAddresses.spec.ts
*Issue #:* bcgov/entity#12571 and bcgov/entity#13510
- changed dropdown edit labels to "Change"
- removed obsolete tooltip
- passed in props to shared date picker
- applied Business Start Date to firm change and firm conversion filings
- passed in props to shared nature of business
- added business start date changed to getters
- added start date to change interface
- added start date to change and conversion filing build methods
- added start date to change and conversion filing parse methods
- misc cleanup
- imported updated nature-of-business
- fixed some unit tests
- app version = 3.7.5
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache …
=> 12571 + 13510: added Business Start Date to firm change and conversion filings + misc fixes

package-lock.json, package.json, src/components/Conversion/ConversionNOB.vue, src/components/common/YourCompany/BusinessStartDate.vue, src/components/common/YourCompany/YourCompany.vue, src/interfaces/stepper-interfaces/PeopleAndRoles/org-person-interface.ts, src/interfaces/store-interfaces/state-interfaces/flags-company-info-interface.ts, src/store/getters/state-getters.ts, src/store/state/state-model.ts, tests/unit/BusinessStartDate.spec.ts
*Issue #:* bcgov/entity#13872
- fixed whitespace around some action buttons
- disabled Business Start Date for firm change filings
- fixed Business Start Date initial validity for corrections
- fixed Business Start Date validity for conversions (flags out of order)
- normalize taxId to prevent false positives
- app version = 3.8.7
=> 13872 Don't allow change of Business Start Date in change filing + misc validation fixes

package-lock.json, package.json, src/App.vue, src/components/common/Actions.vue
*Issue #:* /bcgov/entity#13896
Note to consistently see this error you have to set throttling in dev tools
- Upon clicking Save and Resume and File Now removed setSaving to false because if the page is slow to redirect then the buttons become reenabled.
- App version = 3.8.13 -> 3.8.14
- Replated PR [Create UI](https://github.com/bcgov/business-create-ui/pull/463)
=> 13896 Pages should gray out after clicking Save and Resume Later and File Now, to avoid multiple clicks

package-lock.json, package.json, src/assets/styles/base.scss, src/components/common/YourCompany/NameTranslations/AddNameTranslation.vue, src/components/common/YourCompany/NameTranslations/ListNameTranslation.vue, src/components/common/YourCompany/NameTranslations/NameTranslation.vue, tests/unit/AddNameTranslation.spec.ts, tests/unit/ListNameTranslations.spec.ts, tests/unit/NameTranslation.spec.ts
*Issue #:* bcgov/entity#13345
- removed unneeded  name translation form row/cols
- renamed events and handlers for consistency (within this project and with Create UI)
- changed max name translation length to 50
- cleaned up layouts, classnames and CSS for consistency (with Create UI)
- app version = 3.8.21
=> 13345 Fix name translation length + UI fixes

package-lock.json, package.json, src/components/Alteration/Articles/Articles.vue, src/components/Change/ChangeSummary.vue, src/components/Conversion/ConversionSummary.vue, src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue, src/components/common/PeopleAndRoles/OrgPerson.vue, src/components/common/PeopleAndRoles/PeopleAndRoles.vue, src/components/common/YourCompany/ChangeBusinessType.vue, src/components/common/YourCompany/OfficeAddresses.vue, src/components/common/YourCompany/YourCompany.vue, src/mixins/filing-template-mixin.ts, src/store/getters/state-getters.ts, src/views/Alteration.vue, src/views/Change.vue, src/views/Conversion.vue, src/views/Correction.vue, src/views/Correction/BcCorrection.vue, src/views/Correction/FirmCorrection.vue, src/views/SpecialResolution.vue, tests/unit/BcCorrection.spec.ts, tests/unit/FirmCorrection.spec.ts, tests/unit/SpecialResolution.spec.ts
*Issue #:* bcgov/entity#14520
- renamed isTypeBEN -> isBenefitCompany, etc
- renamed isBaseCorrectionFiling -> isBcCorrectionFiling, etc
- renamed isTypeFirm -> isCorpClassFirm, etc
- renamed BaseCorrection.vue -> BcCorrection.vue
- renamed FmCorrection.vue -> FirmCorrection.vue
- app version = 3.9.8
=> 14520 Renamed entity type getters, etc for consistency between projects

package-lock.json, package.json, src/components/common/YourCompany/NameTranslations/AddNameTranslation.vue, src/components/common/YourCompany/NameTranslations/NameTranslation.vue, tests/unit/AddNameTranslation.spec.ts
Issue #: /https://github.com/bcgov/entity/issues/14545
Corresponding PR in Create UI https://github.com/bcgov/business-create-ui/pull/491
Description of changes:
corp name translation input is now capitalized.
add unit test for name translation input being capitalized.
align AddNameTranslation.vue component and the unit tests to the Create UI
App version 4.4.2 -> 4.4.3
=> 14545 Upper case display for Corp Name Translation

package-lock.json, package.json, src/components/common/PeopleAndRoles/OrgPerson.vue, src/services/business-lookup-services.ts, tests/unit/business-lookup-services.spec.ts
*Issue #:* bcgov/entity#14957
- imported updated shared Business Lookup component
- pass in searchStatus prop to BL component
- changed search status formal parameter to required (not optional)
- updated unit test
- app version - 3.9.13
=> 14957 Quick fix to search all business statuses when replacing DBA

package-lock.json, package.json, src/components/common/EntityInfo.vue, src/interfaces/store-interfaces/state-interfaces/business-information-interface.ts, src/mixins/filing-template-mixin.ts, tests/unit/EntityInfo.spec.ts
*Issue #:* bcgov/entity#15122
- hide Business Number in header
- delete invalid taxid from business object
- app version = 3.9.15
=> 15122 Removed taxid from business object on save

package-lock.json, package.json, src/mixins/filing-template-mixin.ts, tests/unit/EntityInfo.spec.ts
*Issue #:* bcgov/entity#15124
- removed taxId deletion in Filing Template Mixin
- app version = 3.10.1
=> 15124 Restore taxId in business object

package-lock.json, package.json, src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue, src/resources/Change/SP.ts, src/resources/Change/SPOrganization.ts, src/resources/Change/index.ts, src/store/getters/state-getters.ts, src/views/Change.vue, tests/unit/Change.spec.ts, tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#15291
The business has requested that non-staff users should not be able to modify the sole proprietor where the sole proprietor is an organization.  This PR hides the appropriate change button and updates the related help text.
=> 15291 hide sole proprietor change button

package-lock.json, package.json, src/App.vue, src/components/Restoration/YourCompanySummary.vue, src/components/common/YourCompany/NameTranslations/NameTranslation.vue, src/components/common/YourCompany/YourCompany.vue, src/mixins/date-mixin.ts, src/services/date-utilities.ts, src/store/getters/state-getters.ts, src/views/Restoration.vue, tests/unit/state-getters.spec.ts
*Issue #:* /bcgov/entity#15081
This PR makes some minor changes to the YourCompany.vue component to support restoration extension and conversion as shown in the screenshots below:
During a limited restoration extension, no changes to the name block are permitted.
During a limited restoration conversion to full, users can change the entity's name.
=> 15081 add restoration extension and conversion

package-lock.json, package.json, src/enums/routeNames.ts, src/mixins/common-mixin.ts, src/router/routes.ts, tests/unit/FilingTypeToName.spec.ts, tests/unit/Restoration.spec.ts
*Issue #:* /bcgov/entity#15092
Add the following endpoints:  
- /limitedRestorationToFull
- /limitedRestorationExtension
- /fullRestoration
- /limitedRestoration
By separating restorations to different endpoints, we can keep the code cleaner and easier to read.  
=> 15092 - add more restoration endpoints

package-lock.json, package.json, src/App.vue, src/components/ViewWrapper.vue, src/views/Alteration.vue, src/views/Change.vue, src/views/Conversion.vue, src/views/Correction.vue, src/views/Restoration.vue, src/views/SpecialResolution.vue, tests/unit/Alteration.spec.ts, tests/unit/App.spec.ts, tests/unit/Conversion.spec.ts, tests/unit/SpecialResolution.spec.ts
*Issue #:* /bcgov/entity#15092
This is an incremental PR as the changes are potentially disruptive.  The PR removes the fee summaries from App.vue and moves them to a ViewWrapper component that's added to the following views:
- Alteration.vue
- Change.vue
- Conversion.vue
- Correction.vue
- Restoration.vue
- SpecialResolution.vue
By removing the fee summary components from App.vue it gives us more flexibility to handle the actions from FeeSummaryShared differently.
=> 15092 - remove fee summary components from App.vue add to each view instead

package-lock.json, package.json, src/components/Restoration/ExtendTimeLimit.vue
*Issue #:* /bcgov/entity#14974
- As per Ethan's comments, this PR fixes the style and spacing for the Approval type and the limited restoration radio panel.
- Ethan's comments: https://github.com/bcgov/entity/issues/14974#issuecomment-1489055310
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).
=> 14974 Updated extend time limit section to respond to UXA comments

.env.example, .gitignore, devops/vaults.env, package-lock.json, package.json, src/services/date-utilities.ts, src/utils/FetchConfig.ts, tests/unit/FetchConfig.spec.ts, vue.config.js
*Issue #:* [15499](https://github.com/bcgov/entity/issues/15499)
The current VUE_APP_PATH of GCP CD setting cause a null value exception after deploy to firebase. It must be changed to "/" value to avoid exception.
Also, open a ticket to investigate BASE_URL issue. https://github.com/bcgov/entity/issues/15817
=> Fixed the content path issue.

package-lock.json, package.json, src/mixins/filing-template-mixin.ts
*Issue #:* /bcgov/entity#15880
- No longer saving expiry date when doing limited restoration conversion to full
=> 15880 Fixed bug - saving expiry date in limited restoration conversions

package-lock.json, package.json, src/mixins/filing-template-mixin.ts, src/views/LimitedRestorationToFull.vue
*Issue #:* /bcgov/entity#15882
Add missing Pinia actions to resolve issues in DEV.  I didn't realize that Vuex mutations that started with "mutate.." had been renamed to "set..." during the upgrade to Pinia.  This PR removes the calls to "mutate..." and replaces them with calls to the equivalent "set..." instead.
=> 15882 fixes to dev

package-lock.json, package.json, src/components/Restoration/YourCompanySummary.vue
*Issue #:* /bcgov/entity#15080
Fixed alignment based on UXA feedback.
Before:
After fix:
=> 15080-Fix alignment and add a divider

package-lock.json, package.json, src/utils/feature-flag-utils.ts, src/views/Correction.vue
*Issue #:* bcgov/entity#15831
- app version = 4.2.11
- deleted old boolean FF
- added new array FF
- deleted old FF check
- added new FF check
=> 15831 Replaced boolean correction flag with array flag

package-lock.json, package.json, src/components/common/YourCompany/CompanyName/CorrectNameRequest.vue, tests/unit/CorrectNameRequest.spec.ts
*Issue #:* /bcgov/entity#14439
Validate NR format. If the input NR number is valid, normalize the NR number and re-write the result to the input field
For example, input 1234567, it is a valid NR, the NR number input field shows 'NR 1234567'
The acceptable NR numbers are like:
NR 1234567
1234567
NR1234567
NR    1234567
=> validate NR

package-lock.json, package.json, src/components/SpecialResolution/CreateSpecialResolution.vue, src/resources/BreadCrumbResources.ts
Fix dev tools working intermittently - sometimes it would work when you first load the page, but not when you have the page already open and go into the Vue tools.
Fixes this error:
The Pinia store is being used before the Vue instance is initialized I believe
=> Fix dev tools - Update BreadCrumbResources.ts

package-lock.json, package.json, src/App.vue, src/router/routes.ts, src/services/auth-services.ts, src/store/store.ts, src/utils/GetKeycloakRoles.ts, tests/unit/App.spec.ts
*Issue #:* bcgov/entity#16444
- app version = 4.4.2
- moved entity titles from a computed to the routes array
- stop saving auth roles (not used)
- reduced current account retry duration to match other UIs
- used Keycloak roles in LaunchDarkly update
- added titles to routes array
- updated fetchAuthorizations to return roles array
- deleted unused getters and setter
- added getKeycloakRoles
- refactored GetKeycloakRoles (same as in Create UI)
=> 16444 Use Keycloak roles for LaunchDarkly update

package-lock.json, package.json, src/components/common/YourCompany/ChangeBusinessType.vue, src/utils/feature-flag-utils.ts, tests/unit/ChangeBusinessType.spec.ts, tests/unit/setup.ts
*Issue #:* /bcgov/entity#17178
=> 17178 - Alteration - Feature flag - Change Business Types

package-lock.json, package.json, src/components/common/YourCompany/ChangeBusinessType.vue, src/components/common/YourCompany/CorrectName/CorrectNameRequest.vue, src/components/common/YourCompany/EntityName.vue, src/interfaces/store-interfaces/state-interfaces/tombstone-interface.ts, src/store/state/state-model.ts, src/store/store.ts, tests/unit/ChangeBusinessType.spec.ts
*Issue #:* /bcgov/entity#16577
=> 16577 - Alteration - Name Request changes

package-lock.json, package.json, src/components/Alteration/AlterationSummary.vue, src/components/Alteration/Articles/Articles.vue, src/components/Alteration/Articles/ResolutionDates.vue, src/store/store.ts, tests/unit/ResolutionDates.spec.ts
*Issue #:* bcgov/entity#17435
- app version = 4.5.6a
- removed some accessors
- fixed type of Previous Dates prop
- renamed `previousDates` -> `originalResolutions`
- made Resolution Dates Validity dependent on Alteration Filing
- fixed unit test suite
=> 17435 Make resolution dates optional in a correction

package-lock.json, package.json, src/components/SpecialResolution/Resolution.vue, src/components/SpecialResolution/ResolutionEditor.vue, src/components/SpecialResolution/SigningParty.vue, tests/unit/Resolution.spec.ts
*Issue #:* /bcgov/[entity17319](https://github.com/bcgov/entity/issues/17319)
=> 17319 - Date Requirement

package-lock.json, package.json, src/components/common/PeopleAndRoles/OrgPerson.vue
*Issue #:* /bcgov/entity#17347
If the appointmentDate doesn't exist, it's not possible to add in new party members. They get created but don't actually show up.
Fixes this issue:
=> 17347 - Add in appointmentDate for co-op corrections.

package-lock.json, package.json, src/services/legal-services.ts, src/views/Change.vue, src/views/Conversion.vue, tests/unit/legal-services.spec.ts
*Issue #:* bcgov/entity#18238
- app version = 4.7.5
- moved director workaround to LegalServices
- moved parties workaround to LegalServices
- removed workaround from Change
- removed workaround from Conversion
=> 18238 Applied director/party middleInitial/middleName workaround to all filings

package-lock.json, package.json, src/utils/feature-flag-utils.ts, src/views/Alteration.vue, src/views/Change.vue, src/views/Conversion.vue, src/views/SpecialResolution.vue
*Issue #:* bcgov/entity#18456
- app version = 4.7.6
- deleted obsolete "alteration-ui-enabled" FF
- deleted obsolete "change-ui-enabled" FF
- deleted obsolete "conversion-ui-enabled" FF
- removed flag usage from Alteration.vue
- removed flag usage from Change.vue
- removed flag usage from Conversion.vue
- removed flag usage from SpecialResolution.vue
=> 18456 Deleted obsolete feature flags

package-lock.json, package.json, src/components/common/YourCompany/ChangeBusinessType.vue, src/resources/Alteration/ULC.ts
Add in dropdown option for BEN when alterating from ULC
new section in red:
Note this is entire turned off in PROD (via FF).
=> Add in dropdown option for BEN when alterating from ULC

package-lock.json, package.json, src/components/ViewWrapper.vue, src/components/common/PeopleAndRoles/PeopleAndRoles.vue, src/components/common/YourCompany/OfficeAddresses.vue, src/enums/componentsCompanyInfo.ts, src/interfaces/store-interfaces/state-interfaces/flags-company-info-interface.ts, src/mixins/common-mixin.ts, src/mixins/filing-template-mixin.ts, src/store/state/state-model.ts, src/store/store.ts, src/views/LimitedRestorationExtension.vue, src/views/LimitedRestorationToFull.vue, tests/unit/PeopleAndRoles.spec.ts, tests/unit/state-getters.spec.ts
*Issue #:* bcgov/entity#17042
- app version = 4.7.17
- added check before restoring approval type from state filing
- misc cleanup/comments
- fixed some Action declarations
- fixed some filing data typing
- set state filing before parsing draft restoration (which depends on it)
*Collateral fixes:*
- fixed scrollToTop async (and callers)
- fixed scrollToTop typing
- added validation flags comments
- fixed incorrect validation flag order in state model
- fixed mockImplementation variable issue
=> 17042 Fixed draft restoration bug + fixed validation flags error

package.json
- renamed script "serve" to "preview" to prevent confusion with other projects
- removed port specification so that it runs on a different port than "npm run dev" which should also prevent confusion
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).
=> Renamed script to prevent confusion

package-lock.json, package.json, src/components/common/FileUploadPdf.vue, src/services/business-lookup-services.ts, src/services/legal-services.ts, src/utils/FetchConfig.ts, tests/unit/FetchConfig.spec.ts
*Issue #:* bcgov/entity#21134
- app version = 4.9.1
- imported latest Business Lookup shared component
- misc cleanup
- renamed getters and session storage key to better match environment key names
=> 21134 Added continued in entity types to business search

package-lock.json, package.json, src/services/business-lookup-services.ts, tests/unit/business-lookup-services.spec.ts
*Issue #:* bcgov/entity#21718
- app version = 4.9.2
- refactored BusinessLookupServices.search() to use legalTypes parameter (same as in Create UI)
=> 21718 Updated list of legal types to search

package-lock.json, package.json, src/components/common/PeopleAndRoles/OrgPerson.vue
*Issue #:* bcgov/entity#22564
- app version = 4.10.3
- do not show Confirm Name Change checkbox for firm corrections
=> 22564 Do not show Confirm Name Change checkbox for firm corrections

package-lock.json, package.json, src/services/index.ts, src/views/Correction/CoopCorrection.vue, src/views/Correction/CorpCorrection.vue
*Issue #:* bcgov/entity#22978
- app version = 4.10.7
- replaced DateMixin with DateUtilities (coop correction and corp correction only)
- used correct date conversion for original filing date
=> 22978 Fixed original filing date decoding

package-lock.json, package.json, src/components/common/PeopleAndRoles/PeopleAndRoles.vue, src/mixins/filing-template-mixin.ts, src/views/LimitedRestorationExtension.vue, src/views/LimitedRestorationToFull.vue
*Issue #:* /bcgov/entity#16500
- Conversion to Full Restoration or Limited Restoration Extension page, when we edited the Applicant Person's information, click "Save and Resume", then go back - the "Undo" function doesn't work anymore
- Fixed this bug by removing the re-assign officer ID.
- Fixed the bug that removed and added person are not updated, previously in ticket
https://app.zenhub.com/workspaces/entities---olga-65af15f59e89f5043c2911f7/issues/gh/bcgov/entity/23277
(verify this ticket)
- Fixed the bug when the person is a business/corporation, the file and pay fails (fixed the party schema)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license …
=> 16500 - Fixed Restoration People Section Bug

package-lock.json, package.json, src/components/common/YourCompany/ChangeBusinessType.vue, src/mixins/filing-template-mixin.ts, src/resources/Alteration/C.ts, src/resources/Alteration/CBEN.ts, src/resources/Alteration/CUL.ts, src/utils/resource-utils.ts
*Issue #:* /bcgov/entity#23092
- A C company can alter to a C Type (Cont In ULC, C, CCC, BEN)
=> 23092 - Cont in Business Only Alter to Cont in Type

package-lock.json, package.json, src/resources/Alteration/BEN.ts, src/resources/Alteration/CBEN.ts
*Issue #:* /bcgov/entity#24040
- remove CC option from allowed business alteration types for BEN businesses
- remove CCC option from allowed business alteration types for CBEN businesses
- update patch version
=> 24040 Fix Alteration of Company Type Options for BEN/CBEN

package-lock.json, package.json, src/views/Alteration.vue, src/views/SpecialResolution.vue, tests/unit/Alteration.spec.ts, tests/unit/SpecialResolution.spec.ts
*Issue #:* /bcgov/entity#23971
Allow Certify Legal Name section to be editable for regular users. _As per discussion with Mihai, firms and coops are not considered in this ticket._
| Filing Type | is Editable Before | is Editable Now | Notes |
| --- | --- | --- | --- |
| alteration | ❌ | ✔️ |  |
| limitedRestorationExtension | ✔️ | ✔️ |  |
| limitedRestorationToFull | ✔️ | ✔️ |  |
| specialResolution | ❌ | ✔️ |  |
| CorpCorrection | ✔️ | ✔️ |  |
| CoopCorrection | ✔️ | ✔️ | Not considering Coops and Firms at this moment |
| change | ❌ | ❌ | Not considering Coops and Firms at this moment |
| FirmCorrection | ✔️ | ✔️ | Not considering Coops and Firms at this moment |
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> 23971 - allow editable certify legal name

package-lock.json, package.json, src/components/common/YourCompany/ChangeBusinessType.vue, tests/unit/ChangeBusinessType.spec.ts
*Issue #:* /bcgov/entity#24084
- Don't show nameRequestRequiredError when the type change is by Changed Name
=> 24084 - Alteration Name/Type Change Logic

package-lock.json, package.json, src/components/common/YourCompany/ChangeBusinessType.vue, tests/unit/ChangeBusinessType.spec.ts
*Issue #:* /bcgov/entity#24041
- Changed `getUpdatedName` for businesses altering their type to CC/CCC. Talked to Dylan and the preference is to use "COMMUNITY CONTRIBUTION COMPANY LTD." suffix for numbered companies.
=> 24041 Fix alteration of company type issues

package-lock.json, package.json, src/components/common/YourCompany/ChangeBusinessType.vue, src/components/common/YourCompany/EntityName.vue, src/views/Alteration.vue
*Issue #:* /bcgov/entity#23604
- update logic for changing business name
=> 23604 update logic for changing business name

package-lock.json, package.json, src/assets/styles/theme.scss, src/components/Alteration/AlterationSummary.vue, src/components/common/MessageBox.vue, src/components/common/YourCompany/ChangeBusinessType.vue, src/components/common/YourCompany/CorrectName/CorrectName.vue, src/components/common/YourCompany/CorrectName/CorrectNameToNumber.vue, src/components/common/YourCompany/EntityName.vue, src/interfaces/store-interfaces/state-interfaces/tombstone-interface.ts, src/resources/Alteration/C.ts, src/store/state/state-model.ts, src/store/store.ts, src/views/Alteration.vue, tests/unit/ChangeBusinessType.spec.ts, tests/unit/CorrectBusinessType.spec.ts, tests/unit/EntityName.spec.ts
*Issue #:* /bcgov/entity#24297
- update error showing logic - now show error message after user clicks "Done" button in Type Change section
- update error message format - in a message box, red outline
- When there is an error, mark this section invalid
- update wording and language in the error message
- now enable change a named business to numbered, and change its legal type in one filing (Case 7)
- fixed a bug in the "Cancel" button in type change section: it'a BC, 1 director -> enter the NR to change to a CC -> show error: less than 3 director-> click Cancel -> the name change and type change were incorrectly accepted
- fixed the error: change Named business to Numbered -> showing wrong numbered name, always showed "B.C. Ltd". 
By submitting this pull …
=> 24297 - Alteration Business Type & Change Name Update

package-lock.json, package.json, src/components/common/YourCompany/EntityName.vue, tests/unit/EntityName.spec.ts
*Issue #:* /bcgov/entity#20947
- Added `isLimitedRestorationToFull` condition to `shouldShowUndoButton` logic
- Enhanced `nameChangeHandler` to properly handle numbered company names
- Added logic to set legal name for numbered companies to satisfy Legal API requirement
- Updated `shouldShowEditedLabel` to include Limited Restoration to Full scenario
*Notes:*
- This is a temporary easy solution until we can implement the refractory long-term fix in ticket[ #20827](https://github.com/bcgov/entity/issues/20827)
*Test Screenshots:*
Test locally with these scenarios:
**Before Fix** (Using Limited Company as an example):
- After using the incorporation number as the name and clicking "save and resume later"
- Upon resuming, the button incorrectly shows as "Edit" …
=> 20947 - Fix limited restoration to full filing saves or resumes with company Name change

package-lock.json, package.json, src/components/common/Actions.vue, src/store/store.ts, tests/unit/CoopCorrection.spec.ts, tests/unit/state-getters.spec.ts
*Issue #:* /bcgov/entity#25227
FF to conditionally allow empty corrections
=> Edit UI: add FF to conditionally allow "empty corrections"

package-lock.json, package.json, src/store/store.ts, tests/unit/CoopCorrection.spec.ts, tests/unit/state-getters.spec.ts
*Issue #:* bcgov/entity#25243
*Description of changes:* Disable Allowing Empty Articles Input in filing correction.
=> 25243 - Disable Allowing Empty Articles Input in filing correction

package-lock.json, package.json, src/mixins/filing-template-mixin.ts
*Issue #:* /bcgov/entity#25394
In the Register Correction Application output, the date is part of the comment field (i.e. entire text is saved as comment in Comments table). For this reason, the date format needs to be updated in Edit UI.
Date format before was **2025-01-17**
Register Corrections Application filing:
Ledger:
Output:
=> 25394 - Corrections filing update date format

.env.example, package-lock.json, package.json, src/services/business-lookup-services.ts, tests/unit/business-lookup-services.spec.ts
*Issue #:* bcgov/entity#26471
- app version = 4.11.27
- updated reg search URL in example env file
- used separate Axios instance in business lookup services, with own headers that don't include App-Name
=> 26471 Exclude App-Name from reg search API calls

package.json, src/components/common/PeopleAndRoles/OrgPerson.vue, src/resources/Change/SP.ts, src/resources/Conversion/SP.ts, src/resources/Correction/SP.ts, tests/unit/Change.spec.ts
*Issue #:* /bcgov/entity#27519
- Update intro text for SP (change, conversion and correction)
Before:
After:
- Remove legal text above name fields, checkbox under name fields and name change validation for **staff**
=> 27529 - Update Name Change Text for Firms

package-lock.json, package.json, src/interfaces/index.ts, src/mixins/common-mixin.ts, src/views/LimitedRestorationExtension.vue, tests/unit/OfficeAddresses.spec.ts
*Issue #:* /bcgov/entity#29238 
- Make office addresses not editable if they already exist for Limited Restoration Extension
=> 29238 - Addresses for Extension of Restoration Should not be Editable
