bcgov/business-edit-ui

- package-lock.json
- package.json
- updated app name in package.json
- updated package-lock.json
> updated app name in package.json

- .github/workflows/build-master.yml
- k8s/business-edit-ui.dc-srvc-rt-cmap-kcmap.param
- k8s/business-edit-ui.pipeline.param
- k8s/templates/business-edit-ui.dc-srvc-rt-cmap-kcmap.json
- k8s/templates/business-edit-ui.pipeline.json
- package-lock.json
- package.json
*Issue #:* /bcgov/entity#4515
* Updates the values k8s and build-master.yml files for business-edit
> OpenShift and GHA Config Updates

- k8s/README.md
> Updated Comments

- public/config/configuration.json
- public/index.html
- src/App.vue
- src/router/router.ts
- src/utils/config-helper.ts
- src/utils/feature-flags.ts
- src/views/Alteration.vue
- src/views/Correction.vue
*Issue #:* /bcgov/entity#4553
This is partial work that other devs should build upon but I'll be working on something else for a couple of days, so I'm committing this partial code now so others can rebase and use it.
- updated app title in index.html
- updated AC and LD key handling to preempt errors when running locally
- get keycloak roles on app create instead of router
- ongoing development of initApp() to handle filing ID (WIP)
- moved staff check to views instead of router
- ongoing development of Alteration and Correction view (WIP)
> partial work on framework/views/auth/etc

- src/interfaces/filing-interfaces/filing-interface.ts
- src/mixins/filing-template-mixin.ts
*Issue #:* /bcgov/entity#4553
Changes in share structure
> Changes as per the new Share strucuture schema

- src/App.vue
- src/components/Company/CompanyName/CorrectNameRequest.vue
- src/mixins/legal-api-mixin.ts
- src/mixins/name-request-mixin.ts
- cleaned up some code and comments
- removed unnecessary "immediate"
- renamed getApprovedName()
- removed unnecessary "async"s
> misc code cleanup

- src/components/Company/CompanyName/CorrectCompanyName.vue
- src/components/Company/CompanyName/CorrectNameOptions.vue
- src/components/Company/CompanyName/CorrectNameRequest.vue
- src/components/Company/CompanyName/index.ts
- src/components/DefineCompany/BusinessContactInfo.vue
- src/components/DefineCompany/OfficeAddresses.vue
- src/components/DefineCompany/YourCompany.vue
- src/components/common/EntityInfo.vue
- src/interfaces/correction-interfaces/correct-name-interface.ts
- src/interfaces/filing-interfaces/incorporationFiling-interface.ts
- src/interfaces/store-interfaces/state-interface.ts
- src/interfaces/store-interfaces/state-interfaces/businessInformation-interface.ts
- src/interfaces/store-interfaces/state-interfaces/name-request-interface.ts
- src/mixins/name-request-mixin.ts
- src/store/actions/actions-model.ts
- src/store/getters/state-getters.ts
- src/store/index.ts
- src/store/mutations/mutations-model.ts
- src/store/state/state-model.ts
- src/views/Correction.vue
*Issue #:* /bcgov/entity#4843
* Implements sub component to update Company name.
* Refactored store to save IA Snapshot for comparisons and to preserve some UI elements.
* Implemented 'Undo` functionality and UI indicators where correction was made. 
* Updates UI for all Name Correction components as per invision designs. 
* https://projects.invisionapp.com/d/main/#/console/20440642/429271383/preview
> Correct Company Name Component and UI Design Updates

- package.json
- src/App.vue
- src/main.ts
- src/utils/feature-flags.ts
- src/views/Alteration.vue
- src/views/Correction.vue
*Issue #:* /bcgov/entity#4479
- fetch current user and update LD accordingly
- added change handler to LD client
- added options to LD initialize
- cleared flags on LD init error
- implemented updateLdUser()
> set LD user properties

- package-lock.json
- package.json
- we already have release 0.1.0 (ie, initial code)
- this is all changes since then (and up to the deployment to Prod scheduled for end-Sept)
> updated version to 0.2.0

- Jenkinsfiles/deploy-dev.groovy
- Jenkinsfiles/deploy-prod.groovy
- Jenkinsfiles/deploy-test.groovy
- k8s/README.md
*Issue #:* /bcgov/entity#4980
- updated Groovy deploy scripts
- updated README file
> updated deploy scripts + readme

- src/components/DefineCompany/YourCompany.vue
- src/components/IncorporationAgreement/AgreementType.vue
- src/store/getters/state-getters.ts
- src/store/index.ts
- tests/unit/AgreementType.spec.ts
*Issue #:* /bcgov/entity#4765
Modified the agreement type component to include correction features
Added/Modified tests
> Correction - articles component

- package-lock.json
- src/interfaces/filing-interfaces/correctionFiling-interface.ts
- src/mixins/filing-template-mixin.ts
*Issue #:* /bcgov/entity#4946
* Fix to the IA Correction filing structure and Interface
> Fixed IA Correction Structure

- src/components/common/Actions.vue
* File and Pay got hung up on the unneeded check for Correction Filing
> Removed effectiveDate check

- src/assets/styles/base.scss
- src/components/DefineCompany/BusinessContactInfo.vue
- src/components/DefineCompany/CorrectBusinessContactInfo.vue
- src/components/DefineCompany/YourCompany.vue
- src/components/DefineCompany/index.ts
- src/components/IncorporationAgreement/AgreementType.vue
- src/store/getters/state-getters.ts
- tests/unit/BusinessContactInfo.spec.ts
*Issue #:* /bcgov/entity#4891
Modified the registered office contact info to be a reusable component for correction and alteration
Created a wrapper for Correction of registered office contact info
Added tests
Note: Same as Name Request functionality is out  of scope and invision design will be updated soon
> Edit UI - Registered Office Contact Info component

- src/components/Company/CompanyName/CorrectCompanyName.vue
- src/components/Company/CompanyName/CorrectNameOptions.vue
- src/components/Company/CompanyName/CorrectNameRequest.vue
- src/components/Company/CompanyName/CorrectNameToNumber.vue
- src/components/Company/CompanyName/index.ts
- src/components/DefineCompany/YourCompany.vue
- tests/unit/CorrectCompanyName.spec.ts
- tests/unit/CorrectNameOptions.spec.ts
- tests/unit/CorrectNameRequest.spec.ts
- tests/unit/CorrectNameToNumber.spec.ts
- tests/unit/YourCompany.spec.ts
*Issue #:* /bcgov/entity#4984
* Implemented Unit testing for various correction components
* Tweaked YourCompany correction v-chip
> Edit UI: Unit Test Backfill 

- src/components/PeopleAndRoles/ListPeopleAndRoles.vue
- src/components/PeopleAndRoles/OrgPerson.vue
- src/components/PeopleAndRoles/PeopleAndRoles.vue
- src/views/Alteration.vue
- src/views/Correction.vue
- tests/unit/OrgPerson.spec.ts
*Issue #:* /bcgov/entity#4763
- added "wasXXX" methods to simplify template and for future enhancement
- simplified event names
- simplified method names
- fixed staff email bug
- fixed object bugs (by using cloneDeep instead of spread or Object.assign)
- fixed undo bug
> fixed misc bugs

- src/App.vue
- src/components/IncorporationAgreement/AgreementType.vue
- src/components/YourCompany/BusinessContactInfo.vue
- src/components/YourCompany/YourCompany.vue
- src/components/common/Actions.vue
- src/components/common/StaffPayment.vue
- src/interfaces/stepper-interfaces/IncorporationAgreement/incorporation-agreement-interface.ts
- src/interfaces/stepper-interfaces/ShareStructure/create-share-structure-interface.ts
- src/interfaces/stepper-interfaces/YourCompany/define-company-interface.ts
- src/interfaces/stepper-interfaces/common/index.ts
- src/interfaces/stepper-interfaces/common/staff-payment-step-interface.ts
- src/interfaces/store-interfaces/state-interface.ts
- src/interfaces/store-interfaces/state-interfaces/tombstone-interface.ts
- src/store/actions/actions-model.ts
- src/store/getters/state-getters.ts
- src/store/mutations/mutations-model.ts
- src/store/state/state-model.ts
- src/views/Correction.vue
*Issue #:* /bcgov/entity#5092
- Added new flag at the steplevel that indicates whether a correction has been made to that component
- New getter that looks at those change flags to identify whether any correction has been done to the application
- Tied the staff payment validity to the store to enable/disable file and pay
- Changed the showFee summary to look at whether any modification has been done to the filing rather than 'haveChanges'. 
This fixes the problem of fee summary not getting displayed while resuming a draft with correction
- Modified actions buttons to look at the validity and change
- Removed haveCorrection from tombstone
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
> Framework updates and fixes

- src/enums/entityTypes.ts
- src/mixins/filing-template-mixin.ts
- src/resources/certifyStatementResource.ts
- tests/unit/Actions.spec.ts
- tests/unit/AgreementType.spec.ts
- tests/unit/App.spec.ts
- tests/unit/CorrectNameToNumber.spec.ts
- tests/unit/FileAndPayInvalidNameRequestDialog.spec.ts
- tests/unit/OfficeAddresses.spec.ts
- tests/unit/OrgPerson.spec.ts
- tests/unit/ShareStructure.spec.ts
- tests/unit/entityInfo.spec.ts
- tests/unit/nameRequestInfo.spec.ts
*Issue #:* /bcgov/entity#5048
- Enum BC to BEN
- Test fixes
- Filing header default value changed to '' from null
> 5048: Legal Type for Benefit Company from BC to BEN

- src/mixins/filing-template-mixin.ts
> filing validation fix

- src/components/common/Detail.vue
- src/interfaces/stepper-interfaces/common/detail-interface.ts
- src/interfaces/stepper-interfaces/common/index.ts
- src/interfaces/store-interfaces/state-interface.ts
- src/mixins/filing-template-mixin.ts
- src/store/actions/actions-model.ts
- src/store/getters/state-getters.ts
- src/store/mutations/mutations-model.ts
- src/store/state/state-model.ts
*Issue #:* /bcgov/entity#5042
Wiring of detail component
Layout changes
Note: The  UX pin shows a filled style for textarea where as the common component uses the outlined style. I am waiting from confirmation from Scott on this. 
> Detail component changes and wiring

- package-lock.json
- package.json
- src/components/common/Detail.vue
> Updating edit UI to use the updated detail shared component

- src/components/IncorporationAgreement/AgreementType.vue
- src/components/PeopleAndRoles/ListPeopleAndRoles.vue
- src/components/PeopleAndRoles/OrgPerson.vue
- src/components/PeopleAndRoles/PeopleAndRoles.vue
- src/components/YourCompany/BusinessContactInfo.vue
- src/components/YourCompany/CompanyName/CorrectNameOptions.vue
- src/components/YourCompany/CorrectBusinessContactInfo.vue
- src/components/YourCompany/FolioNumber.vue
- src/components/YourCompany/OfficeAddresses.vue
- src/components/YourCompany/YourCompany.vue
- src/components/common/Detail.vue
- src/store/getters/state-getters.ts
- src/store/index.ts
- src/store/state/state-model.ts
- src/views/Alteration.vue
- src/views/Correction.vue
- tests/unit/ListPeopleAndRoles.spec.ts
- tests/unit/OfficeAddresses.spec.ts
- tests/unit/OrgPerson.spec.ts
- tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#4761
- changed PeopleAndRoles buttons to same size as others
- deleted obsolete classes
- fixed/updated layout for Your Company and its sub-components
- fixed Business Contact Info v-chip position (per design)
- cleaned up Office Addresses in prep for development
- changed done-btn selectors to be most specific
> Misc cleanup before development

- src/components/IncorporationAgreement/AgreementType.vue
- src/components/YourCompany/BusinessContactInfo.vue
- src/components/YourCompany/OfficeAddresses.vue
- src/components/YourCompany/YourCompany.vue
- src/enums/addressTypes.ts
- src/enums/index.ts
- tests/unit/OfficeAddresses.spec.ts
- tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#4761
- implemented functionality
- updated misc button layouts same as other components
- fixed some code whitespace
- cleanup
NB: unit tests will be in a separate PR
> Implemented Office Addresses correction functionality

- package-lock.json
- src/components/ShareStructure/ShareStructure.vue
- tests/unit/EditShareStructure.spec.ts
- tests/unit/ShareStructure.spec.ts
*Issue #:* /bcgov/entity#4764
* Fixes / Updates / Adds new unit tests
* small bug fix where Undo'ing corrected Class that now allowed series shares, wasn't resetting the series when 'Undoing' the Share class correction. 
> 4764 Correct Share Structure - Unit Tests & Bug Fix

- src/components/YourCompany/OfficeAddresses.vue
- tests/unit/OfficeAddresses.spec.ts
Issue #: /bcgov/entity#4761
Description of changes:
- unit tests for OfficeAddresses component (WIP)
_NB: There is a Vuetify warning only when running the Jest tests but the code seems to work correctly in both browser and Jest... I looked into it but can't find the problem, so I'm ignoring it for now._
> Office Addresses unit tests

- src/components/YourCompany/CompanyName/CorrectNameRequest.vue
*Issue #:* /bcgov/entity#5082
* Simplified and  updated the form validations for phone and email on name request search. 
> Name Request Correction Form Validators  Update

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#4875
- updated sbc-common-components to 2.3.7
> updated sbc-common-components dependency

- src/components/PeopleAndRoles/ListPeopleAndRoles.vue
- src/components/ShareStructure/ShareStructure.vue
- src/components/common/ActionChip.vue
- src/components/common/Certify.vue
- src/components/common/CompletingParty.vue
- src/components/common/Detail.vue
- src/components/common/StaffPayment.vue
- src/views/Correction.vue
- tests/unit/CompletingParty.spec.ts
*Issue #:* /bcgov/entity#4766
First commit:
- changed some divs to sections
- added IDs to some sections
- a bit of cleanup
Second commit:
- implemented CompletingParty component
- implemented unit tests
- added safety check to formatName()
- adjusted flex sizing for small screens
Third commit:
- lint fix
> implemented Completing Party component

- src/components/ShareStructure/ShareStructure.vue
- tests/unit/ShareStructure.spec.ts
*Issue #:* /bcgov/entity#5202
* Updated and improved functionality of Share Structure correcting as per updated requirements.
* Added series edit form to show the edit form in the proper location when correcting either a Class or Series.
> Share Structure Functionality Updates and Improvements

- src/mixins/filing-template-mixin.ts
- handled optional name translation
> handled optional name translation

- src/components/common/Detail.vue
- src/mixins/filing-template-mixin.ts
- src/store/getters/state-getters.ts
*Issue #:* /bcgov/entity#5203
* Updated Getters and Detail comment component.
* Updated filing template mixin to handle adding and parsing default detail comment.
> Default Detail Comment Fix

- src/components/PeopleAndRoles/PeopleAndRoles.vue
*Issue #:* /bcgov/entity#5076
The subject ticket will contain several changes, which I am breaking it up into smaller PRs.
1. some getters were apparently not firing when their data changed
2. when finding the completing party in a list, removed persons should be ignored
> fix for multiple completing parties

- src/assets/styles/theme.scss
- src/components/PeopleAndRoles/ListPeopleAndRoles.vue
*Issue #:* /bcgov/entity#5076
The subject ticket will contain several changes, which I am breaking it up into smaller PRs.
- changed "Add Role" to "Missing Role"
- updated icon and text color
> changed "Add Role" indicator per designs

- src/components/PeopleAndRoles/PeopleAndRoles.vue
- src/components/ShareStructure/ShareStructure.vue
- src/components/YourCompany/BusinessContactInfo.vue
*Issue #:* /bcgov/entity#5207
* Implements watchers in Contact info and People and Roles to handle 'changed' states when resuming from drafts.
* Bug fix in Share Structure that wouldn't restore series shares after they had been shuffled around in the list placement.
*NOTE:* 
* Developer question...   want me to incorporate this tickets work ( Disabling Actions) into this PR, should only add a few hrs.. 
https://app.zenhub.com/workspaces/entity-5bf2f2164b5806bc2bf60531/issues/bcgov/entity/5115
> 5207 Fee Module Bug ( Various State Fixes )

- src/components/PeopleAndRoles/OrgPerson.vue
- src/components/PeopleAndRoles/PeopleAndRoles.vue
- src/mixins/common-mixin.ts
- tests/unit/OrgPerson.spec.ts
- tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#5076
Commit 1:
- fixed misc whitespace
- formatted checkbox row per designs
- changed checkboxes to same v-model (for validation)
- changed some properties to getters
- added rule to require at least 1 role
- fixed 2 more shallow copy bugs
- only correct person if they have changed (bug)
- reduce checkbox row height when no error
- fixed isRoleLocked bug
- removed unneeded methods in  common mixin
- updated unit tests to look at getters not properties
Commit 2:
- scroll back to top of component after add/edit
> added Roles validation + fixed misc bugs

- src/components/dialogs/NameRequestErrorDialog.vue
- tests/unit/NameRequestErrorDialog.spec.ts
> updated message for NR "Not Found" and "Invalid" cases

- src/components/ShareStructure/ShareStructure.vue
- src/components/YourCompany/CompanyName/CorrectNameRequest.vue
- src/components/common/Actions.vue
- src/store/getters/state-getters.ts
- tests/unit/ShareStructure.spec.ts
*Issue #:* /bcgov/entity#5202
* Quick fix for a getter bug that wasn't evaluating beyond the first Share Class
* Updated Unit testing for above
* Added verbiage for Share Structure
* Updated logic to only validate the NR at file and pay if changes were made to the NR.
* Fixed unwanted population of NR data in NR Change form
> Misc Bug fixes

- src/components/PeopleAndRoles/ListPeopleAndRoles.vue
- src/components/PeopleAndRoles/OrgPerson.vue
- src/components/PeopleAndRoles/PeopleAndRoles.vue
- tests/unit/ListPeopleAndRoles.spec.ts
- tests/unit/OrgPerson.spec.ts
- tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#5074
Fixed/added/updated unit tests for:
- People And Roles component
- List People And Roles component
- Org Person component
> updated unit tests

- src/components/common/EntityInfo.vue
- tests/unit/entityInfo.spec.ts
*Issue #:* /bcgov/entity#5074
* Fixed and updated unit tests for entityInfo component for edit UI.
* Updated some id's in the entityInfo component to make sense with the edit ui.
> EntityInfo unit tests and updates

- src/components/ShareStructure/EditShareStructure.vue
- src/components/ShareStructure/ShareStructure.vue
- src/components/YourCompany/BusinessContactInfo.vue
- src/components/YourCompany/YourCompany.vue
- src/mixins/common-mixin.ts
- src/store/getters/state-getters.ts
- tests/unit/BusinessContactInfo.spec.ts
- tests/unit/ShareStructure.spec.ts
- tests/unit/YourCompany.spec.ts
*Issue #:* /bcgov/entity#5305
* Implemented functionality enhancements on the share structure table, please see attached ticket for checklist...
https://app.zenhub.com/workspaces/entity-5bf2f2164b5806bc2bf60531/issues/bcgov/entity/5305
* Following scenarios handled are laid out in this design ticket... 
https://projects.invisionapp.com/share/FMZ1IBHPD9X#/screens/434176105
* Removed edit functionality on Business Contact info for Corrections Filings
* Updated Unit testing.
* Updated Recognition DateTime to take original Filing Date and Time, not the DateTime of when the Draft Correction Filing was created. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui …
> ShareStructure UX Updates

- src/components/ShareStructure/EditShareStructure.vue
- src/components/ShareStructure/ShareStructure.vue
- src/interfaces/stepper-interfaces/ShareStructure/create-share-structure-interface.ts
- tests/unit/EditShareStructure.spec.ts
- tests/unit/ShareStructure.spec.ts
*Issue #:* /bcgov/entity#5398
* Updated Share structure to utilize UUID for Class and Series ID's
* Fixed interfaces and unit tests
* Fixed Small bug when removing 'ADDED' nested Series.
*Notes:*
* Some changes will need to happen in the Create UI as well, where we initially create and assign ID's to the Share Classes and Series.
> Updated Share Structure ID Implementation

- package-lock.json
- package.json
- src/components/common/Certify.vue
- src/components/common/CertifySection.vue
- src/components/common/index.ts
- src/mixins/date-mixin.ts
- src/store/getters/state-getters.ts
- src/views/Alteration.vue
- src/views/Correction.vue
- tests/unit/Certify.spec.ts
- tests/unit/CertifySection.spec.ts
*Issue #:* /bcgov/entity#4851
* Import and tie Certify Component to Store
* Fixed Unit tests(WIP)
* Fixed time conversion error in Date Mixin
*Notes:*
* Will need to Update Date Mixin in Filings/Create UI to correct bug.
* A small layout refactor is required for the Shared Component to bring in line with similar components, work is captured in this PR: https://github.com/bcgov/bcrs-shared-components/pull/11
> Implemented Certify

- src/components/IncorporationAgreement/AgreementType.vue
- src/components/PeopleAndRoles/OrgPerson.vue
- src/components/PeopleAndRoles/PeopleAndRoles.vue
- fixed checkmark icon colour
- changed Remove button to outlined
> misc style tweaks

- src/components/YourCompany/NameTranslations/CorrectNameTranslation.vue
- src/components/YourCompany/NameTranslations/ListNameTranslation.vue
- src/components/YourCompany/NameTranslations/NameTranslation.vue
- src/interfaces/alteration-interfaces/alteration-interface.ts
- src/interfaces/filing-interfaces/incorporationApplication-interface.ts
- src/interfaces/store-interfaces/state-interfaces/name-translation-interface.ts
- src/interfaces/store-interfaces/state-model-interface.ts
- src/mixins/filing-template-mixin.ts
- src/store/getters/state-getters.ts
- src/store/mutations/mutations-model.ts
- src/store/state/state-model.ts
- tests/unit/Alteration.spec.ts
- tests/unit/ListNameTranslations.spec.ts
> 5701 name translation schema change

- package-lock.json
- package.json
- src/components/common/Actions.vue
- src/main.ts
- src/utils/feature-flags.ts
- src/views/Alteration.vue
- src/views/Correction.vue
- tests/unit/Actions.spec.ts
*Issue #:* /bcgov/entity#5591
- updated version to 0.5.1
- changed File and Pay to use isPaymentActionRequired flag
> redirect to Pay URL depending on payment flag

- src/assets/styles/base.scss
- src/assets/styles/overrides.scss
- src/assets/styles/theme.scss
- src/components/YourCompany/BusinessContactInfo.vue
- src/components/YourCompany/CompanyName/CorrectNameOptions.vue
- src/components/YourCompany/CompanyName/CorrectNameRequest.vue
- src/components/YourCompany/CompanyName/CorrectNameToNumber.vue
- src/components/YourCompany/NameTranslations/CorrectNameTranslation.vue
- src/components/YourCompany/YourCompany.vue
- src/components/dialogs/ConfirmDialog.vue
- src/main.ts
- tests/unit/YourCompany.spec.ts
*Issue #:* /bcgov/entity#5106
- Ux Adjustments based on feedback for Edit UI, more specifically the Change of Name related components.
- More global changes to follow in next ticket.
> Name Request UX/Syle Additions/Adjustments

- src/components/YourCompany/CorrectBusinessType.vue
- src/components/YourCompany/NameTranslations/NameTranslation.vue
- src/components/common/EntityInfo.vue
- src/enums/entityTypes.ts
- src/mixins/common-mixin.ts
- src/mixins/name-request-mixin.ts
- tests/unit/CorrectBusinessType.spec.ts
*Issue #:* /bcgov/entity#5102
* Added conversions from Name Request Entity Types to align with Colin/Lear
* Updated Entity info to display original Entity types before any corrections/alterations
> Edit UI: NR -> Colin Type Conversions

- src/assets/styles/base.scss
- src/assets/styles/overrides.scss
- src/assets/styles/theme.scss
- src/components/YourCompany/CorrectBusinessType.vue
- src/components/YourCompany/YourCompany.vue
- src/components/common/ContactInfo.vue
- src/components/common/EntityInfo.vue
- src/main.ts
- src/mixins/common-mixin.ts
- src/mixins/date-mixin.ts
- tests/unit/CorrectBusinessType.spec.ts
- tests/unit/YourCompany.spec.ts
*Issue #:* /bcgov/entity#5102 & /bcgov/entity#5106 
* Some style, UX additions and fixes.
* Updated Benefit Company help display, to only show after selection.
> UX/Style Updates

- src/App.vue
- src/assets/styles/overrides.scss
- src/components/Summary/AlterationSummary.vue
- src/components/Summary/NoFeeSummary.vue
- src/components/YourCompany/CorrectBusinessType.vue
- src/components/dialogs/ConfirmDialog.vue
- src/store/getters/state-getters.ts
- src/views/Alteration.vue
*Issue #:* /bcgov/entity#5172
* Fixed selectedEntityType bug where state wasn't being established on a re-mount after changes.
* Fixed conflicts bug where it would incorrectly see a conflict when their wasn't a new nr.
* Some style tweaks to the dialogs.
* Minor verbiage updates.
> 5172 - UX/functionality improvements

- src/App.vue
- src/components/YourCompany/YourCompany.vue
*Issue #:* /bcgov/entity#5172
* Fixes the conditions of which the confirmation dialog appears. ie.. don't show for Correction Actions
* Fixes logic around 'Corrected' tag and display of Business Type on Business Name changes. ie... don't show for Corrections.
> Alteration/Correction Dialog Fix

- package.json
- src/components/YourCompany/OfficeAddresses.vue
- tests/unit/OfficeAddresses.spec.ts
*Issue #:* /bcgov/entity5027
-  Added conditions to addresses section to allow editing only when it is a correction
- Added some styling
> Added conditions to editing address and added some styles

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#5025
* Updated to latest Contact Info version
> Contact-Version-Bump

- src/components/YourCompany/NameTranslations/ListNameTranslation.vue
*Issue #:* /bcgov/entity#5028
Ready to go to dev after these changes are merged as per Tracey's comments:
https://app.zenhub.com/workspaces/entity-5bf2f2164b5806bc2bf60531/issues/bcgov/entity/5028
> 5028 - style updates for drop down menu items

- package-lock.json
- package.json
- src/components/Summary/AlterationSummary.vue
- src/components/common/StaffPayment.vue
- src/views/Alteration.vue
- src/views/Correction.vue
- tests/unit/AddNameTranslation.spec.ts
*Issue #:* /bcgov/entity#6735
- updated endpoint in getServerDate()
- moved setFilingData out of StaffPayment component
- StaffPayment component now emits haveChanges event
- AlterationSummary component now emits haveChanges event
- updated Alteration view to handle StaffPayment changes
- updated Alteration view to handle AlterationSummary changes (ie, FED atm)
- updated Correction view to handle StaffPayment changes
- misc lint fixes
> updated filing data code (fees)

- src/components/Articles/Articles.vue
- src/components/Articles/CompanyProvisions.vue
- src/components/Articles/ResolutionDates.vue
- src/components/ShareStructure/ShareStructures.vue
- src/components/Summary/AlterationSummary.vue
- src/components/Summary/NoFeeSummary.vue
- src/components/YourCompany/CorrectBusinessType.vue
- src/components/common/DatePicker.vue
- src/components/common/EffectiveDateTime.vue
- src/components/dialogs/ResolutionDateDialog.vue
- src/mixins/filing-template-mixin.ts
- tests/unit/Articles.spec.ts
- tests/unit/CompanyProvisions.spec.ts
- tests/unit/CompletingParty.spec.ts
- tests/unit/EffectiveDateTime.spec.ts
- tests/unit/NameRequestErrorDialog.spec.ts
- tests/unit/ResolutionDates.spec.ts
*Issue #:* /bcgov/entity#5179
- added not-edit mode to Resolution Dates component
- updated Alteration Summary component
- added Resolution Dates unit tests
- updated/fixed some other unit tests
- misc cleanup
> Resolution or Court Order Dates on review page

- package-lock.json
- package.json
- src/components/PeopleAndRoles/CurrentDirectors.vue
- src/components/Summary/AlterationSummary.vue
- src/components/YourCompany/YourCompany.vue
- src/interfaces/store-interfaces/state-interfaces/businessInformation-interface.ts
- src/mixins/filing-template-mixin.ts
- src/store/getters/state-getters.ts
- fixed a typo
- fixed Founding Date snafu
- updated app version to 0.5.19
- changed review page logic for Resolution/Court Order Dates component
> small fixes

- package-lock.json
- package.json
- src/components/Summary/AlterationSummary.vue
- src/interfaces/stepper-interfaces/common/effectiveDateTime-interface.ts
- src/store/mutations/mutations-model.ts
- src/store/state/state-model.ts
- tests/unit/Alteration.spec.ts
- tests/unit/AlterationSummary.spec.ts
*Issue #:* /bcgov/entity#5476
- fixed FED valid flag coming from wrong place
- cleaned up FED interface
- updated app version to 0.5.22
> Fixed FED valid flag

- .gitignore
- package-lock.json
- package.json
- src/mixins/date-mixin.ts
- src/mixins/filing-template-mixin.ts
- tests/unit/date-mixin.spec.ts
Issue #: /bcgov/entity#6763
Description of changes:
- fixed FED datetime format for API submission
- added unit test
> 6763 Fix FED datetime format for API submission

- package-lock.json
- package.json
- src/components/Summary/DocumentsDelivery.vue
- src/components/common/CertifySection.vue
- src/enums/reviewSummaryFlags.ts
- src/interfaces/alteration-interfaces/valid-flags-interface.ts
- src/interfaces/stepper-interfaces/common/documentDelivery-interface.ts
- src/store/getters/state-getters.ts
- src/store/mutations/mutations-model.ts
- src/store/state/state-model.ts
- src/views/Alteration.vue
- tests/unit/DocumentDelivery.spec.ts
*Issue #:* /bcgov/entity#5475
- validation for document delivery section
- validation for certify section
- ui updates and alignments
> 5475 - UI fixes based on feedback (mostly validation)

- src/components/Summary/DocumentsDelivery.vue
- src/components/common/CertifySection.vue
- src/store/mutations/mutations-model.ts
*Issue #:* /bcgov/entity#5475
- allow for undefined email (non staff)
> 5475 - tiny fix validation for non staff

- package-lock.json
- package.json
- public/config/configuration.json
- src/App.vue
- src/components/Summary/AlterationSummary.vue
- src/components/YourCompany/CompanyName/CorrectCompanyName.vue
- src/components/YourCompany/CompanyName/CorrectNameOptions.vue
- src/components/YourCompany/CompanyName/CorrectNameRequest.vue
- src/components/YourCompany/CompanyName/CorrectNameToNumber.vue
- src/components/YourCompany/CorrectBusinessType.vue
- src/components/YourCompany/YourCompany.vue
- src/mixins/common-mixin.ts
- tests/unit/CorrectNameRequest.spec.ts
- tests/unit/DocumentDelivery.spec.ts
*Issue #:* /bcgov/entity#5173
- changed some v-layout/v-flex to v-row/v-col
- fixed some whitespace and alignment issues
- uppercased NR number (on input and display)
- uppercased company name (on input and display)
> - changed some v-layout/v-flex to v-row/v-col

- src/components/Summary/DocumentsDelivery.vue
> remove space

- package-lock.json
- package.json
> use latest certify component

- package-lock.json
- package.json
- src/components/YourCompany/CompanyName/CorrectCompanyName.vue
- tests/unit/AlterationSummary.spec.ts
- tests/unit/NameTranslation.spec.ts
*Issue #:* /bcgov/entity#5173
- removed company name capitalization in input field (ie, uppercase on display only)
> Removed company name capitalization on input

- src/App.vue
- src/components/Articles/CompanyProvisions.vue
- src/components/Summary/AlterationSummary.vue
*Issue #:* /bcgov/entity#5177
* Added review text when there is changes to the pre-existing company provisions.
* Fixed draft bug, where state wasn't restoring.
* Added Scroll to top effect when transitioning to Summary Mode.
> Pre-existing Comp Provisions Review

- package-lock.json
- package.json
- src/App.vue
- src/components/Summary/AlterationSummary.vue
- src/components/Summary/NoFeeSummary.vue
- src/components/dialogs/AccountAuthorizationDialog.vue
- src/components/dialogs/DeleteErrorDialog.vue
- src/components/dialogs/FetchErrorDialog.vue
- src/components/dialogs/FileAndPayInvalidNameRequestDialog.vue
- src/components/dialogs/PaymentErrorDialog.vue
- src/enums/index.ts
- src/enums/summaryActions.ts
- src/mixins/common-mixin.ts
- tests/unit/AlterationSummary.spec.ts
- tests/unit/NoFeeSummary.spec.ts
- update app version
- updated shared enums dependency
- updated shared fee summary dependency
- moved fee summary affix to main page
- added fee summary error message (WIP)
- misc cleanup
- updated alteration section header
- updated phone ext per uxpin
- deleted obsolete local enum
> Top level changes (first part)

- src/App.vue
- updated main page column breakpoints for Tracey to play with and determine any further changes
> Updated main page breakpoints

- .github/workflows/cd.yml
- Dockerfile
- Makefile
- devops/vaults.json
1. Switch master branch to main branch;
2. Migrated the environments to 1password;
3. Modify CD flow on makefile;
4. Modify CI/CD GHA scripts;
> Enable main branch and CICD flow changes.

- src/App.vue
- src/components/Summary/DocumentsDelivery.vue
*Issue #:* /bcgov/entity#7145
* Updated error msg for review page.
* Updated validations for Documents section.
> Fixed review text and updated Document validations

- src/App.vue
- leave underlying components rendered when Confirm Delete All modal is displayed
> Updated modal background

- tests/unit/App.spec.ts
- added some unit tests to increase code coverage
> Added unit tests

- package-lock.json
- package.json
- src/App.vue
*Issue #:* /bcgov/entity#7245
- imported latest Fee Summary
- cleaned up some logic
> Imported latest Fee Summary

- nginx.conf
- package-lock.json
- package.json
*Issue #:* /bcgov/entity#7263
- added nginx config to disable index.html caching
- updated sbc-common-components dependency
> Updated sbc-common-components dependency + updated caching config

- package-lock.json
- package.json
- src/components/ShareStructure/ShareStructures.vue
- src/store/getters/state-getters.ts
- tests/unit/ShareStructures.spec.ts
*Issue #:* /bcgov/entity#5693
* Implements validation logic for minimum ShareClasses
* Adds unit testing.
*Note:*
* Applies to both Alterations and Corrections. No additional design/rules were commented on in the ticket for Corrections.
> Prevent ShareClass Removal

- package-lock.json
- package.json
- src/assets/styles/base.scss
- src/components/common/CertifySection.vue
- src/components/common/StaffPayment.vue
- src/store/getters/state-getters.ts
*Issue #:* /bcgov/entity#7145
* Updated App and component validations
* Minor updated to apply a form level validation to Staff Payment and Certify components.
> Certify/Staff Payment Field Validations

- package-lock.json
- package.json
- src/components/common/StaffPayment.vue
*Issue #:* /bcgov/entity#7145
* Fixed WHEN to prompt field level validations. ie only prompt them if the user has selected an option. 
> Staff Payment Field Validation Update

- package-lock.json
- package.json
- src/components/Articles/Articles.vue
- src/components/Articles/CompanyProvisions.vue
- src/components/Articles/ResolutionDates.vue
- src/components/Summary/AlterationSummary.vue
- src/components/common/EffectiveDateTime.vue
- src/enums/alterationCompanyInfoFlags.ts
- src/interfaces/alteration-interfaces/valid-components-interface.ts
- src/interfaces/alteration-interfaces/valid-flags-interface.ts
- src/mixins/common-mixin.ts
- src/store/getters/state-getters.ts
- src/store/state/state-model.ts
- tests/unit/Articles.spec.ts
- tests/unit/CompanyProvisions.spec.ts
- tests/unit/ResolutionDates.spec.ts
*Issue #:* /bcgov/entity#6274
- Added component validation to CompanyProvisions and ResolutionDates
- Added tests
**This is part of 6274 regarding the component validations when the user clicks on "Review and Certify" only.**
> 6724 - Alteration UI - Added component validation to CompanyProvisions and ResolutionDates

- package-lock.json
- package.json
- src/components/common/CertifySection.vue
- src/store/mutations/mutations-model.ts
- src/views/Alteration.vue
- tests/unit/Actions.spec.ts
- tests/unit/state-getters.spec.ts
> 7353 Fixes for certify section for both alteration flows

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#7505
- updated share-structure import
> Imported fixed share-structure component

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#7488
- updated share structure import (max digits rule)
> Imported fixed share-structure component (max digits rule)

- package-lock.json
- package.json
- src/views/Alteration.vue
*Issue #:* /bcgov/entity#7473
- Updated CourtOrderPoa component
> 7473- Update CourtOrderPoa

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#6682
Fix bug and disable browser autocomplete on address input
> Update sbc-common-component version

- package-lock.json
- package.json
- public/config/configuration.json
- src/utils/config-helper.ts
*Issue #:* /bcgov/entity#7694
- updated Auth Api Config workaround
- updated local configuration
> Updated auth config key loading

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#6682
Update the version number of sbc-common-components
> Update the version number of sbc-common-components

- package-lock.json
- package.json
This should NOT have been merged.
Reverts bcgov/business-edit-ui#198
> Revert "Update the version number of sbc-common-components"

- package-lock.json
- package.json
- src/App.vue
*Issue #:* /bcgov/entity#7764
- Added PaySystemAlert to business-edit-ui
> 7764 - Added PaySystemAlert to business-edit-ui

- Makefile
- devops/vaults.json
- public/config/configuration.json
- src/utils/config-helper.ts
*Issue #:* bcgov/entity#7849
Fixed the LD flag key name issue.
> Fixed the LD flag key name issue

- .github/workflows/ci.yml
- Dockerfile
- k8s/templates/bc.yaml
*Issue #:* /bcgov/entity#8609
- Updated node version
> 8609 - Updated node version

- package-lock.json
- package.json
- tests/unit/ShareStructures.spec.ts
*Issue #:* /bcgov/entity#8780
- Updated share-structure version
> 8780 - Updated share-structure version

- src/interfaces/alteration-interfaces/alteration-interface.ts
- src/mixins/filing-template-mixin.ts
*Issue #:* /bcgov/entity#8934
* Allow a draft alteration to be loaded blank.
* Only Include changed sections into Alteration filing.
> Alteration Structural Changes

- package-lock.json
- package.json
- src/enums/nameRequestTypes.ts
- src/mixins/name-request-mixin.ts
- tests/unit/CorrectNameRequest.spec.ts
*Issue #:* /bcgov/entity#8984
* UI updates around validation to prevent INVALID scenarios when the NR has no expiration date set.
* Include check on NR purpose type and allow Change of Name NRs and Conversion NR's.
*Note* - There is also some pending validator updates required in the LEAR API under the same ticket#
> NR validation updates

- package-lock.json
- package.json
- src/components/PeopleAndRoles/ListPeopleAndRoles.vue
- src/components/PeopleAndRoles/OrgPerson.vue
- src/components/PeopleAndRoles/PeopleAndRoles.vue
- src/components/common/CompletingParty.vue
- src/enums/incorporatorTypes.ts
- src/interfaces/stepper-interfaces/PeopleAndRoles/org-person-interface.ts
- tests/unit/Actions.spec.ts
- tests/unit/App.spec.ts
- tests/unit/CompletingParty.spec.ts
- tests/unit/ListPeopleAndRoles.spec.ts
- tests/unit/OrgPerson.spec.ts
- tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#6742
- Changed organization terms; 
- Fixed tests;
- Updated version
** PLEASE DO NOT MERGE YET **
Legal-api changes need to be in sync.
> 6742 - Changed organization terms

- devops/vaults.json
- package-lock.json
- package.json
- public/config/configuration.json
- src/App.vue
- src/resources/BreadCrumbResource.ts
- src/utils/config-helper.ts
*Issue #:* /bcgov/entity#10747
* Added configuration for BCROS Home Url
* Updated Home Crumb for non-staff
*NOTE:* - The updated routes require additional in configuration in DEV, TEST, PROD ENV's to add the following:
Dev = https://yfthig-dev.web.app/
Test = https://www.bcregistry.daxiom.ca/
Prod = https://www.bcregistry.gov.bc.ca/
> Updated HomeCrumb and Config

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#10922
* Updated Common Component version
> Updated CC Version

- package-lock.json
- package.json
- src/App.vue
- src/main.ts
- src/views/auth/Signin.vue
- src/views/auth/Signout.vue
- tests/unit/App.spec.ts
*Issue #:* /bcgov/entity#10853
- initialize token service in main instead of App (needed to sync session before routing)
- redirect to BC Registry for login, then return here
- after logout, redirect to login page
- app version = 0.6.28
> 10853 Login and logout redirects

- package-lock.json
- package.json
- src/App.vue
- src/components/common/Actions.vue
- src/main.ts
- src/mixins/date-mixin.ts
- src/resources/BreadCrumbResource.ts
- src/utils/config-helper.ts
- src/utils/feature-flags.ts
- src/utils/index.ts
- src/utils/navigate.ts
- src/views/auth/Signin.vue
- tests/unit/Actions.spec.ts
- tests/unit/Alteration.spec.ts
- tests/unit/App.spec.ts
*Issue #:* /bcgov/entity#10999
- stored account id in session
- created "navigate" function to automatically add accountid parameter
- replaced window.location.assign with new function
- fixed date/time conversions broken by Node 12
- updated breadcrumb resources to append account id
- app version = 0.6.29
> 10999 Handle account id sync

- package-lock.json
- package.json
- src/assets/styles/base.scss
- src/assets/styles/layout.scss
- src/assets/styles/theme.scss
- src/components/common/YourCompany/YourCompany.vue
- src/resources/Correction/BenefitCompanyStatementResource.ts
*Issue #:* /bcgov/entity#10687
* Implements latest version of contact info
* Layout updates to meet latest requirements for general layout
> Contact Info Ux

- README.md
- codecov.yaml
> Update codecov configuration.

- devops/vaults.json
> Add naics-api to vault

- package-lock.json
- package.json
- src/App.vue
- src/components/Edit/AlterationSummary.vue
- src/components/common/YourCompany/YourCompany.vue
- src/enums/index.ts
- src/mixins/date-mixin.ts
- src/store/mutations/mutations-model.ts
- src/utils/config-helper.ts
- tests/unit/AlterationSummary.spec.ts
- tests/unit/App.spec.ts
- tests/unit/ChangeSummary.spec.ts
*Issue #:* /bcgov/entity#11324
* Implements latest version of Fee Summary
* Updates to support latest version of Fee Summary
* Utilize founding date/start date for Firms
* Updated/added to 'Leave without Saving' functionality for Alterations/Change Filings.
* Remove 'Change' action in Summary Header for Change Filings
* Updated unit testing
* Updated identifier check to allow Firms
> Fee Summary Versioning + Start Date Implementation

- package-lock.json
- package.json
- src/components/common/EffectiveDateTime.vue
- src/interfaces/filing-interfaces/incorporationApplication-interface.ts
- src/mixins/filing-template-mixin.ts
- src/store/state/state-model.ts
- tests/unit/filing-template-mixin.spec.ts
*Issue #:* /bcgov/entity#10873
* Updated type for phone extension
* removed obsolete rule for future effective date
> Updated Extension Type and Date Rule

- package-lock.json
- package.json
- src/components/common/YourCompany/OfficeAddresses.vue
- src/enums/index.ts
- src/enums/officeTypes.ts
- src/interfaces/stepper-interfaces/YourCompany/address-interface.ts
- src/mixins/filing-template-mixin.ts
- src/store/getters/state-getters.ts
- tests/unit/App.spec.ts
- tests/unit/ChangeSummary.spec.ts
- tests/unit/filing-template-mixin.spec.ts
*Issue #:* /bcgov/entity#10686
* Implements `businessOffice` office type for Firms
* Added dynamic office type to handle the varying office types for addresses
* Updated getters to utilize dynamic office type in retrieval and comparisons
* Updated unit testing 
> Updated Office Address Parsing

- package-lock.json
- package.json
- src/assets/styles/base.scss
- src/assets/styles/layout.scss
- src/components/Edit/ChangeSummary.vue
- src/components/common/BcRegContacts.vue
- src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue
- src/components/common/PeopleAndRoles/OrgPerson.vue
- src/components/common/PeopleAndRoles/PeopleAndRoles.vue
- src/enums/actionTypes.ts
- src/enums/orgPersonTypes 2.ts
- src/enums/partyTypes 2.ts
- src/enums/roleTypes.ts
- src/interfaces/resource-interfaces/resource-interface.ts
- src/interfaces/stepper-interfaces/PeopleAndRoles/org-person-interface.ts
- src/interfaces/stepper-interfaces/common/help-section-interface 2.ts
- src/mixins/filing-template-mixin.ts
- src/mixins/legal-api-mixin.ts
- src/resources/Correction/BenefitCompanyStatementResource.ts
- src/resources/Edit/ChangeFirm/generalPartnership.ts
- src/resources/Edit/ChangeFirm/soleProprietorship.ts
- src/store/getters/state-getters.ts
- tests/unit/Alteration.spec.ts
- tests/unit/ChangeSummary.spec.ts
- tests/unit/ListPeopleAndRoles.spec.ts
- tests/unit/OrgPerson.spec.ts
- tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#1173
* Implements Partners, Orgs Adding/Editing improved UX and functionality
* Updates Corrections stying
* Incorporates unique badges dependant on content changed, preserves badges for Corrections
* Updates unit test
* updated action to support multiple if required.
* removed V1 api override for /filings GET requests.
> Implements Partners, persons and orgs

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/CurrentDirectors.vue
*Issue #:* /bcgov/entity#11793
* Removed obsolete code due to api update
> Removed obsolete code

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/OrgPerson.vue
*Issue #:* /bcgov/entity#11907
>  Edit UI  fix the "Optional" in all the address fields

- .github/workflows/ci.yml
- Dockerfile
- k8s/templates/bc.yaml
- package-lock.json
- package.json
*Issue #:* /bcgov/entity#11879
update note version from 14.17.5 to 16.14.2
> 11879_update_node_version

- package-lock.json
- package.json
- src/App.vue
- src/mixins/filing-template-mixin.ts
- src/views/Change.vue
- tests/unit/filing-template-mixin.spec.ts
*Issue #:* /bcgov/entity#11936
- don't prepopulate CP name when staff
- added appointment date to CP
- deleted empty officer and address properties to work around schema issues
- convert middleInitial -> middleName when fetching firm snapshot
- app version = 3.0.4
> 11936 Fix save structure errors and middle name issue

- package-lock.json
- package.json
- src/components/Conversion/ConversionNOB.vue
- src/components/common/CourtOrderPoa.vue
- src/components/common/YourCompany/YourCompany.vue
- src/interfaces/store-interfaces/state-interfaces/business-information-interface.ts
- src/mixins/filing-template-mixin.ts
- src/services/auth-services.ts
- src/views/Conversion.vue
- tests/unit/BusinessContactInfo.spec.ts
*Issue #:* /bcgov/entity#11954
- handle empty contacts from Auth Info call
- if put contacts fails, try post contacts
- fixed Court Order POA errors
- handle addresses not found for conversion
- fixed Business Contact Info unit tests
- misc cleanup
- app version = 3.1.5
> 11954 Misc conversion filing updates

- package-lock.json
- package.json
- src/components/Conversion/ConversionNOB.vue
- src/views/Conversion.vue
*Issue #:* [/bcgov/entity#12206](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/12206)
> 12206 Edit UI - handle business addresses with HTTP 404 for SP/GP conversion filings

- package-lock.json
- package.json
- src/components/Conversion/ConversionNOB.vue
- src/components/Conversion/ConversionSummary.vue
- src/components/common/YourCompany/NatureOfBusiness.vue
- src/components/common/YourCompany/YourCompany.vue
- src/mixins/filing-template-mixin.ts
- src/store/getters/state-getters.ts
- tests/unit/ConversionNatureOfBusiness.spec.ts
*Issue #:* /bcgov/entity#11954
Commit 1:
- used getters to simplify Nature Of Business
- show NOB even when missing NAICS code
- used getters to simplify Conversion NOB
- don't send empty NAICS Code in conversion filing
Commit 2:
- imported latest shared NOB
- simplified NatureOfBusiness
- fixed Contact Info button right alignment
- fixed typos
- app version = 3.1.8
> 11954 Fixed filing issue + misc NOB tweaks

- package-lock.json
- package.json
- src/components/Change/ChangeSummary.vue
- src/components/Conversion/ConversionSummary.vue
- src/components/common/PeopleAndRoles/PeopleAndRoles.vue
- src/components/common/YourCompany/BusinessContactInfo.vue
- src/interfaces/resource-interfaces/resource-interface.ts
- src/resources/Alteration/BenefitCompanyResource.ts
- src/resources/Alteration/CooperativeResource.ts
- src/resources/Change/GeneralPartnershipResource.ts
- src/resources/Change/SoleProprietorshipResource.ts
- src/resources/Conversion/GeneralPartnershipResource.ts
- src/resources/Conversion/SoleProprietorshipResource.ts
- src/store/getters/state-getters.ts
- src/store/mutations/mutations-model.ts
- src/store/state/resource-model.ts
*Issue #:* /bcgov/entity#11954
**Known bug: still can't add proprietor/partner. I will work on it next.**
Commit 1:
- prevent unneeded business contact updates
- don't set Have Changes flag for business contact updates
Commit 2:
- show help blurb for change and conversion filings
- show conversion SP add buttons and mininum proprietor error text
- added conversion GP help blurb
- added conversion SP help blurb and help text
- added minimum proprietor getter
- deleted unneeded resource entity type
> 11954 More change/conversion fixes and cleanup

- package-lock.json
- package.json
- src/components/Alteration/TransactionalFolioNumber.vue
- src/components/Conversion/ConversionNOB.vue
- src/components/common/Actions.vue
- src/components/common/PeopleAndRoles/OrgPerson.vue
- src/components/common/YourCompany/BusinessContactInfo.vue
- src/components/common/YourCompany/ChangeBusinessType.vue
- src/components/common/YourCompany/NameTranslations/AddNameTranslation.vue
- src/components/common/YourCompany/YourCompany.vue
- src/store/getters/state-getters.ts
- tests/unit/OrgPerson.spec.ts
- tests/unit/YourCompany.spec.ts
- tests/unit/state-getters.spec.ts
*Issue #:* /bcgov/entity#11954
- renamed some getters for consistency
- cleaned up Add/Edit Org/Person layout/whitespace
- fixed schema naming error
- cleaned up Contact Info edit button CSS
- fixed Conversion NOB validation style
- deleted unnecessary Conversion NOB changes flag
- misc cleanup
- update unit tests
- app version = 3.1.10
> 11954 More conversion fixes and cleanup

- package-lock.json
- package.json
- src/resources/Correction/BenefitCompanyStatementResource.ts
- src/resources/Correction/GeneralPartnershipResource.ts
- src/resources/Correction/SoleProprietorshipResource.ts
- src/store/getters/state-getters.ts
- src/views/Correction/BenCorrection.vue
- src/views/Correction/FmCorrection.vue
- tests/unit/Actions.spec.ts
- tests/unit/state-getters.spec.ts
*Issue #:* /bcgov/entity#12399
- moved initial filing data to resources
- fixed firm correction filing type code
- temporarily fixed firm correction data changed getter
- temporarily fixed firm correction filing valid getter
- fixed some unit tests
- app version = 3.2.2
> 12399 Fixed firm correction fee code, changed and valid getters

- package-lock.json
- package.json
- src/components/Correction/AgreementType.vue
- src/components/Correction/CompletingParty.vue
- src/components/common/PeopleAndRoles/PeopleAndRoles.vue
- src/components/common/ShareStructure/ShareStructures.vue
- src/components/common/YourCompany/BusinessContactInfo.vue
- src/components/common/YourCompany/YourCompany.vue
- src/enums/filingTypes.ts
- src/interfaces/filing-interfaces/registration-filing-interface.ts
- src/mixins/filing-template-mixin.ts
- src/store/getters/state-getters.ts
- tests/unit/Actions.spec.ts
- tests/unit/FolioInformation.spec.ts
- tests/unit/ListPeopleAndRoles.spec.ts
- tests/unit/OrgPerson.spec.ts
- tests/unit/PeopleAndRoles.spec.ts
- tests/unit/state-getters.spec.ts
*Issue #:* /bcgov/entity#12399
- updated "get original filing" getters for ease of use
- app version = 3.2.3
> 12399 Misc improvements for future developmemnt

- package-lock.json
- package.json
- src/components/Conversion/ConversionNOB.vue
- src/components/Correction/CompletingParty.vue
- src/components/common/PeopleAndRoles/PeopleAndRoles.vue
- src/components/common/YourCompany/BusinessContactInfo.vue
- src/components/common/YourCompany/FolioInformation.vue
- src/components/common/YourCompany/YourCompany.vue
- src/mixins/filing-template-mixin.ts
- src/store/getters/state-getters.ts
- src/views/Correction/FmCorrection.vue
*Issue #:* /bcgov/entity#12399
- more getter cleanup
- fixed firm correction data issues (ie, get original data from snapshot, not original filing)
- updated ConversionNOB chip and button labels
- app version = 3.2.4
> 12399 Fixed firm correction data issues + more cleanup for future development

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/OrgPerson.vue
*Issue #:* /bcgov/entity#12730
**DO NOT MERGE until the subject ticket is approved for inclusion into this week's deployment (Release 13.5a).**
- fixed address population bug
- app version = 3.2.5a
> 12730 Fixed address edit bug

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#12309
- app version = 3.3.0
> 12309 Updated app version

- package-lock.json
- package.json
- src/services/business-lookup-services.ts
*Issue #:* /bcgov/entity#12758
- provided fallback for account id
- app version = 3.3.1
> 12758 Fixed missing account id

- nginx.conf
*Issue #:* /bcgov/entity#12758
- updated app_header to allow access to Business Lookup API
> 12758 Update nginx.conf

- package-lock.json
- package.json
- src/assets/styles/layout.scss
- src/components/common/PeopleAndRoles/OrgPerson.vue
- tests/unit/FmCorrection.spec.ts
- tests/unit/OrgPerson.spec.ts
*Issue #:* /bcgov/entity#12309
- added SP/GP unit tests
- fixed a test suite
- app version = 3.3.2
> 12309 Added SP/GP unit tests

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/OrgPerson.vue
- src/services/business-lookup-services.ts
*Issue #:* /bcgov/entity#12757
- cleared invalid BN (length < 9)
- catch fetch address error
- filtered out search results without valid identifier
- app version = 3.3.3
> 12757 Added safety checks

- package-lock.json
- package.json
- src/App.vue
- src/components/common/Detail.vue
- src/components/common/ShareStructure/ShareStructures.vue
- src/components/common/StaffPayment.vue
- src/components/common/YourCompany/NameTranslations/NameTranslation.vue
- src/mixins/filing-template-mixin.ts
- src/views/Correction.vue
*Issue #:* /bcgov/entity#12550
- implemented reload() to avoid partial load issues
- don't render SbcFeeSummary until we have filing type code and entity type
- init prev detail comment (for resume)
- fixed Add Share button layout
- misc cleanup
- app version = 3.3.4
> 12550 Fixed misc correction issues

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#12872
- incremented app version to 3.4.3 (that was missed in previous PR due to rebase)
> 12872 bumped app version

- package-lock.json
- package.json
- src/interfaces/store-interfaces/state-interfaces/correction-information-interface.ts
- tests/unit/OfficeAddresses.spec.ts
- tests/unit/PeopleAndRoles.spec.ts
- tests/unit/state-getters.spec.ts
*Issue #:* [/bcgov/entity#12574](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/12574)
- state-getters.spec.ts
- PeopleAndRoles.spec.ts
- OfficeAddresses.spec.ts (first test case)
> 12574 SP/GP Correction Edit UI - Update Business Address component

- package-lock.json
- package.json
- src/components/common/YourCompany/CompanyName/CorrectNameToNumber.vue
- src/interfaces/store-interfaces/state-interfaces/name-request-interface.ts
- src/mixins/filing-template-mixin.ts
- tests/unit/Actions.spec.ts
- tests/unit/BenCorrection.spec.ts
- tests/unit/BusinessContactInfo.spec.ts
- tests/unit/CompletingParty.spec.ts
- tests/unit/CorrectCompanyName.spec.ts
- tests/unit/CorrectNameRequest.spec.ts
- tests/unit/CorrectNameToNumber.spec.ts
- tests/unit/EntityInfo.spec.ts
- tests/unit/FmCorrection.spec.ts
- tests/unit/FolioInformation.spec.ts
- tests/unit/ListPeopleAndRoles.spec.ts
- tests/unit/OfficeAddresses.spec.ts
- tests/unit/OrgPerson.spec.ts
- tests/unit/PeopleAndRoles.spec.ts
- tests/unit/date-mixin.spec.ts
- tests/unit/filing-template-mixin.spec.ts
- tests/unit/state-getters.spec.ts
*Issue #:* /bcgov/entity#12872
- app version = 3.4.5
> 12872 fixed unit tests

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue
- src/components/common/PeopleAndRoles/OrgPerson.vue
- src/components/common/PeopleAndRoles/PeopleAndRoles.vue
- src/resources/Correction/BenefitCompanyStatementResource.ts
- tests/unit/ListPeopleAndRoles.spec.ts
- tests/unit/OrgPerson.spec.ts
- tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#12999
- removed Completing Party and Incorporator role checkboxes, list items, getters, etc
- removed Add Corporation and Add Completing Party buttons, etc
- removed Completing Party dialog, methods, props, etc
- updated validators
- renamed section title
- misc cleanup
- app version = 3.4.6
> 12999 Removed BEN IA correction completing party and incorporator

- package-lock.json
- package.json
- src/components/common/YourCompany/CompanyName/CorrectNameRequest.vue
- src/components/common/YourCompany/YourCompany.vue
- src/interfaces/resource-interfaces/resource-interface.ts
- src/mixins/name-request-mixin.ts
- src/resources/Correction/BenefitCompanyStatementResource.ts
- src/resources/Correction/GeneralPartnershipResource.ts
- src/resources/Correction/SoleProprietorshipResource.ts
- tests/unit/CorrectNameRequest.spec.ts
- tests/unit/name-request-mixin.spec.ts
*Issue #:* [/bcgov/entity#12572](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/12572)
-  reuse the existing component
- only support "new NR" version for name change
- added `isEntityTypeFirm` in name-request-mixin.ts
> 12572 SP/GP Correction Edit UI - Update Business Name

- package-lock.json
- package.json
- src/App.vue
- src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue
- src/components/common/PeopleAndRoles/OrgPerson.vue
- src/components/common/PeopleAndRoles/PeopleAndRoles.vue
- src/components/common/YourCompany/BusinessContactInfo.vue
- src/components/common/YourCompany/ChangeBusinessType.vue
- src/components/common/YourCompany/OfficeAddresses.vue
- src/components/common/YourCompany/YourCompany.vue
- src/interfaces/alteration-interfaces/alteration-interface.ts
- src/mixins/common-mixin.ts
- src/mixins/filing-template-mixin.ts
- src/store/getters/state-getters.ts
- tests/unit/App.spec.ts
- tests/unit/BusinessContactInfo.spec.ts
- tests/unit/ListPeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#13059
- renamed isChangeRegFiling -> isFirmChangeFiling for clarity
- app version = TBD
> 13059 Misc fixes

- package-lock.json
- package.json
- src/mixins/filing-template-mixin.ts
*Issue #:* /bcgov/entity#13169
- fix deleted share classes/series not filtered out of filing
- app version = 3.5.8
> 13169 Fix alteration share deletion

- package-lock.json
- package.json
- src/components/common/YourCompany/FolioInformation.vue
- src/services/auth-services.ts
Small bug fix, adding in new flag for special resolution filing as well. 
> Fix folio number call to sbc-auth.

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/PeopleAndRoles.vue
- src/components/common/YourCompany/ChangeBusinessType.vue
- src/components/common/YourCompany/OfficeAddresses.vue
- src/components/common/YourCompany/SummaryDefineCompany.vue
- src/components/common/YourCompany/YourCompany.vue
- src/mixins/enum-mixin.ts
- src/mixins/filing-template-mixin.ts
- src/mixins/index.ts
*Issue #:* /bcgov/entity#13059
- added Enum Mixin (copied from FilingsUI)
- updated Corrected Filing Name (in detail comments section)
- some cleanup of unused imports/declarations
- app version = 3.5.10
> 13059 Update default detail comment

- package-lock.json
- package.json
- src/services/business-lookup-services.ts
- tests/unit/business-lookup-services.spec.ts
*Issue #:* /bcgov/entity#13145
> 13145 update business search services

- package-lock.json
- package.json
- src/mixins/filing-template-mixin.ts
- src/store/getters/state-getters.ts
- src/views/Correction/FmCorrection.vue
*Issue #:* /bcgov/entity#13197
- save CertifiedBy as empty string if it doesn't exist (ie, staff-error correction)
- add Completing Party only for client-error correction
- deleted console.log from unit test
- app version = 3.5.14
> 13197 Fix misc firm correction issues

- package-lock.json
- package.json
- src/mixins/filing-template-mixin.ts
*Issue #:* /bcgov/entity#13197
- default correction type to CLIENT (for testing)
- app version = 3.5.15
> 13197 Set default correction type to CLIENT

- package-lock.json
- package.json
- tests/unit/CommonCompletingParty.spec.ts
*Issue #:* [/bcgov/entity#13058](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/13058)
- updated common completing party version
- added unit test template for later
> 13058 Update Common Completing Party

- package-lock.json
- package.json
- src/interfaces/store-interfaces/state-interfaces/correction-information-interface.ts
- src/mixins/filing-template-mixin.ts
*Issue #:* bcgov/entity#13199
- updated NAICS data in Correction Information interface
- save/restore NAICS object in filing.correction.business
- app version = 3.5.16
> 13199 Misc schema updates

- package-lock.json
- package.json
- src/components/common/YourCompany/AssociationType.vue
- src/components/common/YourCompany/BusinessContactInfo.vue
- src/components/common/YourCompany/FolioInformation.vue
- src/components/common/YourCompany/YourCompany.vue
- src/enums/componentsCompanyInfo.ts
- src/interfaces/store-interfaces/state-interfaces/flags-company-info-interface.ts
- src/store/getters/state-getters.ts
- src/store/state/state-model.ts
- tests/unit/YourCompany.spec.ts
*Issue #:* /bcgov/entity#12896
Also minor changes for 12894, 12895
Fix validation for AssociationType.vue.
Make BusinessContactInfo instant update for Special Resolution.
Fix folio information tooltip Changed -> Changes Saved on instant update.
Update package version.
> 12896 - UI for Changes to Registered company contact information

- package-lock.json
- package.json
- src/components/Alteration/AlterationSummary.vue
- src/components/common/YourCompany/NameTranslations/AddNameTranslation.vue
- src/enums/componentsReviewCertify.ts
- src/interfaces/stepper-interfaces/PeopleAndRoles/people-and-roles-interface.ts
- src/interfaces/stepper-interfaces/ShareStructure/create-share-structure-interface.ts
- src/interfaces/stepper-interfaces/common/detail-interface.ts
- src/interfaces/stepper-interfaces/common/index.ts
- src/interfaces/stepper-interfaces/common/staff-payment-step-interface.ts
- src/interfaces/store-interfaces/state-interfaces/flags-review-certify-interface.ts
- src/interfaces/store-interfaces/state-model-interface.ts
- src/mixins/filing-template-mixin.ts
- src/store/getters/state-getters.ts
- src/store/mutations/mutations-model.ts
- src/store/state/state-model.ts
- tests/unit/Actions.spec.ts
- tests/unit/FmCorrection.spec.ts
- tests/unit/PeopleAndRoles.spec.ts
- tests/unit/state-getters.spec.ts
*Issue #:* bcgov/entity#13199
First commit:
- added detail-section to ComponentsReviewCertify and FlagsReviewCertify validation
- deleted obsolete Detail interface
- deleted obsolete StaffPaymentStep interface
- deleted obsolete PeopleAndRoles valid flag, etc
- deleted obsolete ShareStructure valid flag, etc
- deleted obsolete Detail valid flag, etc
- moved staff payment to stateModel.staffPayment, etc
- moved detail comment to stateModel.detailComment, etc
- updated hasCorrectionDataChanged()
- updated isSpecialResolutionValid()
- updated isCorrectionValid()
- misc cleanup
- app version = 3.5.19
Second commit:
- renamed hasNameTranslationChanged -> haveNameTranslationsChanged
- normalized org-person fields in havePeopleAndRolesChanged()
By submitting this pull …
> 13199 Updated hasCorrectionDataChanged() and isCorrectionValid(), etc

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/PeopleAndRoles.vue
*Issue #:* bcgov/entity#12790
- updated hasMinimumPartners error message
- app version = 3.5.20
> 12790 Updated Minimum Partners message

- package-lock.json
- package.json
- src/App.vue
- src/components/common/Actions.vue
*Issue #:* bcgov/entity#10495
- added Filing ID to Return URL in App.vue
- added Filing ID to Return URL in Actions.vue
- misc cleanup
- app version = 3.5.28
> 10495 Added Filing ID to Return URL

- package-lock.json
- package.json
- src/components/SpecialResolution/CreateSpecialResolution.vue
- src/components/common/TransactionalFolioNumber.vue
*Issue #:* /bcgov/entity#13289
* validation colour and label fix
> Special Resolution Review and Certify Page#13289

- package-lock.json
- package.json
- src/components/common/YourCompany/YourCompany.vue
- tests/unit/YourCompany.spec.ts
*Issue #:* /bcgov/entity#13162
> 13162 Edit UI: firm correction should use NAICS not NOB component

- src/components/common/CourtOrderPoa.vue
- src/components/common/StaffPayment.vue
*Issue #:* /bcgov/entity#13485
Minor changes for Staff Payment / Court Order
> 13485 - Fix for StaffPayment/Court Order and Plan of Arrangement not in card.

- package-lock.json
- package.json
- src/components/Alteration/Articles/Articles.vue
- src/components/Alteration/Articles/CompanyProvisions.vue
- src/components/Alteration/Articles/ResolutionDates.vue
- src/interfaces/filing-interfaces/correction-filing-interface.ts
- src/interfaces/store-interfaces/state-interfaces/correction-information-interface.ts
- src/mixins/filing-template-mixin.ts
- src/store/getters/state-getters.ts
- src/views/Correction/BenCorrection.vue
- tests/unit/Articles.spec.ts
- tests/unit/BenCorrection.spec.ts
- tests/unit/CompanyProvisions.spec.ts
- tests/unit/ResolutionDates.spec.ts
*Issue #:* /bcgov/entity#13079
*Issue #:* /bcgov/entity#12989
- added articles component to BEN IA corrections
- added resolution dates
- added pre-existing conditions
- added the CORRECTION badges
- added Undo functionality
- added to correction "is valid" method
- added to correction "has changed" method
- updated correction build and parse methods
- unit tests
> 13079 Resolution Dates Collab Pre-existing Conditions for BEN IA correction filings

- package-lock.json
- package.json
- src/components/common/YourCompany/BusinessContactInfo.vue
- src/components/common/YourCompany/YourCompany.vue
- src/interfaces/filing-interfaces/conversion-interfaces.ts
- src/mixins/filing-template-mixin.ts
- tests/unit/YourCompany.spec.ts
*Issue #:* /bcgov/entity#12690
- conditionally removed component `BusinessContactInfo`
- updated validation
- updated the build method and the parse method
> 12690 Edit UI: Conversion filing - remove Business contact component

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/OrgPerson.vue
*Issue #:* /bcgov/entity#13160
- Removed the highlighted box from deactivated checkbox
- the rest of the work completed for this ticket was done in [bcrs-shared-components 150](https://github.com/bcgov/bcrs-shared-components/pull/150)
- imported the the shareStructure component from the work done in the PR above
> 13160 BEN corrections UI adjustments

- package-lock.json
- package.json
- src/views/Correction/BenCorrection.vue
- src/views/Correction/FmCorrection.vue
- tests/unit/BenCorrection.spec.ts
*Issue #:* /bcgov/entity#13553
- add Completing Party component (for Client Error only)
- place above Detail component
- unit tests
> 13553 Edit UI: BEN IA correction should prompt for Completing Party

- package-lock.json
- package.json
- src/views/Correction/BenCorrection.vue
- src/views/Correction/FmCorrection.vue
*Issue #:* /bcgov/entity#13553
- Fix the StaffPayment component section number
- Hide the Certify section for staff error for BEN IA correction
> 13553 Fix StaffPayment and Certify sections

- package-lock.json
- package.json
- public/config/configuration.json
- src/utils/fetchConfig.ts
*Issue #:* /bcgov/entity#13695
- based off of filings-UI PR bcgov/business-filings-ui/pull/391]
- app version = 3.7.9
- sorted keys in local config file
- changed console.log -> console.info
- use regex to id business ids including new c type
> 13695 id "Cxxxxxxx" business ids

- package-lock.json
- package.json
- src/mixins/filing-template-mixin.ts
- src/store/state/state-model.ts
*Issue #:* /bcgov/entity#13723
- make truthy special resolution validation flag in `parseChangeRegFiling`
> 13723 Edit UI - Review and Confirm step shows missing required info when there is none missing

- package-lock.json
- package.json
- src/components/common/CompletingParty.vue
- src/enums/accountTypes.ts
- src/store/getters/state-getters.ts
Signed-off-by: Kial Jinnah <kialjinnah@gmail.com>
*Issue #:* /bcgov/entity#13822
> sp/gp sbc flow - make completing party editable

- package-lock.json
- package.json
- src/store/getters/state-getters.ts
*Issue #:* /bcgov/entity#13849
> 13849 handle empty address for conversion filing

- package-lock.json
- package.json
- src/App.vue
*Issue #:* /bcgov/entity#13861
Remove d-flex, update sbc-common-components to 3.0.3.
> 13861 - Update business-edit-ui to use sbc-common-components 3.0.3.

- package-lock.json
- package.json
- src/components/common/YourCompany/BusinessStartDate.vue
- tests/unit/BusinessStartDate.spec.ts
*Issue #:* bcgov/entity#13913
- removed min/max date for conversion filings
- changed "Unknown" -> "(Not entered)" (consistent with other components)
- updated validity logic
- app version = 3.8.5
> 13913 Changes to Business Start Date

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/CurrentDirectors.vue
- src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue
*Issue #:* bcgov/entity#13914
- updated BaseAddress import (sbc-common-components)
- cleaned up CurrentDirectors styling
- cleaned up ListPeopleAndRoles styling
- app version = 3.8.6
> 13914 BaseAddress styling fixes

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#13875
- Reduce Tech debt update NOB shared component from 1.1.1 -> 1.2.0
- Tested with Conversion and change filings (two places the edit UI uses NOB)
- version 3.8.8
> Update NOB shared component

- package-lock.json
- package.json
- src/interfaces/store-interfaces/action-interface.ts
- src/store/getters/state-getters.ts
- tests/unit/Actions.spec.ts
- tests/unit/state-getters.spec.ts
*Issue #:* bcgov/entity#13958
- check different valid flags for client vs staff BEN correction
- app version = 3.8.9
> 13958 Fixed BEN correction validity check

- package-lock.json
- package.json
- src/enums/componentsReviewCertify.ts
- src/interfaces/store-interfaces/state-interfaces/flags-review-certify-interface.ts
- src/mixins/common-mixin.ts
- src/store/state/state-model.ts
*Issue #:* bcgov/entity#13924
- improved validateAndScroll()
- fixed property order in stateModel
- app version = 3.8.10
> 13924 fixed validation

- package-lock.json
- package.json
- src/components/common/DocumentsDelivery.vue
- src/components/common/StaffPayment.vue
- src/store/state/state-model.ts
- src/views/Alteration.vue
- src/views/Change.vue
- src/views/Correction/BenCorrection.vue
- src/views/SpecialResolution.vue
*Issue #:* bcgov/entity#13981
- fixed Staff Payment initial validation
- initialized staff payment option to NONE
- pre-selected No Fee in BEN correction
- misc cleanup
- app version = 3.8.11
> 13981 Fixed Staff Payment initial validation

- package-lock.json
- package.json
- src/App.vue
- src/views/Change.vue
- src/views/Conversion.vue
- src/views/SpecialResolution.vue
*Issue #:* /bcgov/entity#13987
- app version = 3.8.12
- removed unnecessary setters
- added $nexttick after setting app validate to allow validation to happen
> 13987 invalid Court Order component should prevent filing

- package-lock.json
- package.json
- src/components/common/YourCompany/YourCompany.vue
- src/interfaces/resource-interfaces/resource-interface.ts
- src/mixins/name-request-mixin.ts
- src/resources/Alteration/BenefitCompanyResource.ts
- src/resources/Change/GeneralPartnershipResource.ts
- src/resources/Change/SoleProprietorshipResource.ts
- src/resources/Conversion/GeneralPartnershipResource.ts
- src/resources/Conversion/SoleProprietorshipResource.ts
- src/resources/Correction/BenefitCompanyStatementResource.ts
- src/resources/Correction/GeneralPartnershipResource.ts
- src/resources/Correction/SoleProprietorshipResource.ts
- src/resources/SpecialResolution/CooperativeResource.ts
- src/store/state/resource-model.ts
- tests/unit/name-request-mixin.spec.ts
*Issue #:* bcgov/entity#14019
- deleted obsolete nameRequestType from  resource interface and files
- added optional title and description to resource interface
- fixed bug in isNrValid()
- added missing nameRequestTypes to GP and SP change resource files
- misc cleanup
- app version = 3.8.10a
- simplified logic to display NR change for all filing types
> 14019 Fixed name change NR issue

- package-lock.json
- package.json
- src/components/common/YourCompany/OfficeAddresses.vue
- tests/unit/OfficeAddresses.spec.ts
*Issue #:* bcgov/entity#14080
- added missing code to retain original address IDs
- added unit tests
- app version = 3.8.14
> 14080 Fixed missing address IDs

- package-lock.json
- package.json
- src/mixins/filing-template-mixin.ts
*Issue #:* bcgov/entity#14195
- deleted "id" property from added parties
- updated some comments for clarity
- app version = 3.8.17
The rules are detailed in the ticket. Some screenshots are attached there, too.
> 14195 Deleted id property from added parties

- package-lock.json
- package.json
- public/config/configuration.json
- tests/unit/FetchConfig.spec.ts
*Issue #:* bcgov/entity#13696
- deleted obsolete config key
- added test suite for FetchConfig()
- app version = 3.8.18
> 13696 Added test suite for FetchConfig.ts

- package-lock.json
- package.json
*Issue #:* bcgov/entity#13232
- upgraded vue test-utils to v1.3.3
- app version = 3.8.19
> 13232 Upgraded vue-test-utils

- package-lock.json
- package.json
- src/mixins/name-request-mixin.ts
- tests/unit/name-request-mixin.spec.ts
*Issue #:* bcgov/entity#14364
- allowed Conditional as valid NR state
- app version = 3.8.22
> 14364 Allowed Conditional as valid NR state

- package-lock.json
- package.json
- src/App.vue
*Issue #:* /bcgov/entity/issues/14301
Support for SBC Staff
> Feature 14301 - Support for SBC Staff

- package-lock.json
- package.json
- src/shims-tsx.d.ts
- src/shims-vue.d.ts
- tests/unit/ListPeopleAndRoles.spec.ts
- tests/unit/PeopleAndRoles.spec.ts
- tests/unit/business-lookup-services.spec.ts
*Issue #:* bcgov/entity#13887
- restored shim files (apparently needed by unit tests)
- unit tests for business-lookup-service.ts
- unit tests for ListPeopleAndRoles.vue
- unit tests for PeopleAndRoles.vue
- app version = 3.9.1
> 13887 Unit tests

- package-lock.json
- package.json
- src/services/business-lookup-services.ts
- tests/unit/business-lookup-services.spec.ts
*Issue #:* bcgov/entity#14505
- removed SP from list of legal types to search for
- app version = 3.9.2
> 14505 Removed SP from business lookup

- package-lock.json
- package.json
- src/mixins/filing-template-mixin.ts
- src/resources/Alteration/CommunityContributionCompanyResource.ts
- src/resources/Alteration/LimitedCompanyResource.ts
- src/resources/Alteration/UnlimitedLiabilityCompanyResource.ts
- src/resources/Alteration/index.ts
- src/store/getters/state-getters.ts
- src/views/Alteration.vue
- tests/unit/Alteration.spec.ts
*Issue #:* /bcgov/entity#14437
- added support for BC/ULC/CCC alterations
- added resource file for BC limited company
- added resource file for community contribution company
- added resource file for unlimited company
> 14437 Edit UI: add support for BC/ULC/CCC alterations

- package-lock.json
- package.json
- src/components/Alteration/Articles/Articles.vue
- src/components/Alteration/Articles/ResolutionDates.vue
- src/components/Change/ChangeSummary.vue
- src/components/Conversion/ConversionSummary.vue
- src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue
- src/components/common/PeopleAndRoles/OrgPerson.vue
- src/components/common/PeopleAndRoles/PeopleAndRoles.vue
- src/components/common/YourCompany/ChangeBusinessType.vue
- src/components/common/YourCompany/OfficeAddresses.vue
- src/components/common/YourCompany/YourCompany.vue
- src/mixins/filing-template-mixin.ts
- src/store/getters/state-getters.ts
- src/views/Alteration.vue
- src/views/Change.vue
- src/views/Conversion.vue
- src/views/Correction.vue
- src/views/Correction/BaseCorrection.vue
- src/views/Correction/FmCorrection.vue
- src/views/SpecialResolution.vue
- tests/unit/BaseCorrection.spec.ts
*Issue #:* bcgov/entity#14520
- changed isBenCorrectionFiling -> isBaseCorrectionFiling
- renamed isEntityTypeXXX -> isTypeXXX
- refactored dirValid -> haveMinimumDirectors
- refactored haveRequiredProprietor
- refactored haveMinimumPartners
- renamed BenCorrection.vue -> BaseCorrection.vue
- added some getters
- moved unused getters from filing-template-mixin to components that need them
- changed Correction view to use dynamic components
- app version = 3.9.7
> 14520 Code expansion for BC/CCC/ULC + cleanup

- .github/workflows/cd.yml
- .github/workflows/ci.yml
*Issue #:* /bcgov/entity/14257
Upgrade codecov and checkout version number.
> 14257-upgrade ci/cd

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/OrgPerson.vue
*Issue #:* bcgov/entity#14546
- imported latest Business Lookup shared component
- pass in "editableBusinessName" flag
- app version = 3.9.10
> 14546 Update to allow editable business name when replacing DBA

- package-lock.json
- package.json
- src/components/common/YourCompany/OfficeAddresses.vue
*Issue #:* bcgov/entity#14941
- fixed code typo
- app version = 3.9.12
> 14941 Fixed records-delivery address bug

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/OrgPerson.vue
- src/services/business-lookup-services.ts
- tests/unit/business-lookup-services.spec.ts
*Issue #:* bcgov/entity#14957
- imported updated shared Business Lookup component
- pass in searchStatus prop to BL component
- changed search status formal parameter to required (not optional)
- updated unit test
- app version = 3.9.10a
> 14957 Quick fix to search all business statuses when replacing DBA 

- package-lock.json
- package.json
- src/components/Alteration/Articles/ResolutionDates.vue
- src/interfaces/store-interfaces/state-interfaces/business-information-interface.ts
- src/interfaces/store-interfaces/state-interfaces/correction-information-interface.ts
- src/mixins/filing-template-mixin.ts
- src/store/state/state-model.ts
*Issue #:* bcgov/entity#14766
- changed correction.correctedFilingDate to optional
- changed correction.parties to required
- deleted invalid NAICS props (no impact)
- ensured class and series hasMaximumShares and hasRightsOrRestrictions is boolean
- fixed resolution dates button heights
- app version - 3.9.14
> 14766 Fixed schema error

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue
- src/resources/Change/SP.ts
- src/store/getters/state-getters.ts
- tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#15291
HOTFIX based based on commit 1df7fff098c436b4ac64f4cec54dbf17fdd9e900  This PR is identical to #444 except it's based on release branch `release-3.9.15`
> 15291 hotfix hide sole proprietor change button v2

- package-lock.json
- package.json
- src/resources/Change/SPOrganization.ts
- src/resources/Change/index.ts
- src/views/Change.vue
- tests/unit/Change.spec.ts
*Issue #:* /bcgov/entity#15291
Hotfix issue identified by Mihai where subtitle shown to organizational sole proprietors should be different from individual sole proprietors.  Version: 3.9.15b
> 15291 - hotfix v3.9.15b - add subtitle for organizational sole proprietors

- package-lock.json
- package.json
- src/components/common/ErrorContact.vue
- tests/unit/ErrorContact.spec.ts
*Issue #:* /bcgov/entity#15543
Update contact phone number
> update contact phone number

- package-lock.json
- package.json
- src/components/Restoration/ExtendTimeLimit.vue
- src/components/Restoration/YourCompanySummary.vue
- src/components/ViewWrapper.vue
- src/enums/componentsCompanyInfo.ts
- src/enums/index.ts
- src/interfaces/restoration-interfaces/restoration-interface.ts
- src/interfaces/store-interfaces/state-interfaces/flags-company-info-interface.ts
- src/interfaces/store-interfaces/state-interfaces/restoration-state-interface.ts
- src/interfaces/store-interfaces/state-model-interface.ts
- src/mixins/date-mixin.ts
- src/mixins/filing-template-mixin.ts
- src/services/date-utilities.ts
- src/services/legal-services.ts
- src/store/actions.ts
- src/store/getters.ts
- src/store/mutations.ts
- src/store/state/state-model.ts
- src/views/LimitedRestorationExtension.vue
- src/views/LimitedRestorationToFull.vue
- tests/unit/ExtendTimeLimit.spec.ts
- tests/unit/FilingTypeToName.spec.ts
- tests/unit/state-getters.spec.ts
*Issue #:* /bcgov/entity#14974
- Added the extension time limit section
- Added extension section in review and certify page
- To summarize and show all the new components/work, here's a small demo:
https://user-images.githubusercontent.com/122301442/227372318-d75062c2-a2a4-4b44-9b33-66cfec0dc119.mp4
> Extend limited restoration time limit

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#14974
Forgot to update package version after latest rebase. 
> 14974 Updated package version after rebase

- package-lock.json
- package.json
- src/components/ViewWrapper.vue
- src/components/common/QuestionWrapper.vue
- src/interfaces/alteration-interfaces/alteration-interface.ts
- src/interfaces/restoration-interfaces/restoration-interface.ts
- src/interfaces/store-interfaces/state-interfaces/business-information-interface.ts
- src/interfaces/store-interfaces/state-interfaces/correction-information-interface.ts
- src/mixins/filing-template-mixin.ts
- src/store/state/state-model.ts
- tests/unit/ViewWrapper.spec.ts
- tests/unit/filing-template-mixin.spec.ts
*Issue #:* bcgov/entity#15684
Commit 1:
- app version = 4.0.6
- updated browserslist
- misc cleanup
- updated some filing business objects to match saved data
- changed some properties to be non-optional per schema
- changed some properties to be optional per schema
- save only required filing.business properties in all filings
- added missing Contact Point to Special Resolution filing (per schema)
- added missing snapshot parsing for business info
- updated a unit test
Commit 2:
- added missing Confirm Dialog to ViewWrapper
- sorted getters, actions and local properties
> 15684 Cleaned up saved business object + fixed Cancel button / missing dialog

- package-lock.json
- package.json
- src/store/actions.ts
- src/views/LimitedRestorationExtension.vue
- src/views/LimitedRestorationToFull.vue
*Issue #:* bcgov/entity#15878
- app version = 4.0.7
- added console.log to action
- added missing getters/actions
- deleted unneeded getters/actions
> 15878 Cleanup

- package-lock.json
- package.json
- src/components/common/YourCompany/BusinessContactInfo.vue
*Issue #:* bcgov/entity#15962
- app version = 4.2.5
- enabled Update Contact Info for all filings (NB: is not rendered for Conversion)
> 15962 Fixed contact info update for restorations

- package-lock.json
- package.json
- src/mixins/filing-template-mixin.ts
*Issue #:* bcgov/entity#15964
- app version = 4.2.6
- added nameRequest object to full restoration filing
> 15964 Fix restoration NR object

- package-lock.json
- package.json
- src/components/Restoration/ExtendTimeLimit.vue
- src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue
- src/components/common/PeopleAndRoles/PeopleAndRoles.vue
- src/mixins/filing-template-mixin.ts
- src/views/LimitedRestorationExtension.vue
- src/views/LimitedRestorationToFull.vue
*Issue #:* bcgov/entity#15919
Commit 1:
- app version = 4.2.7
- changed max expiry months from 36 to default (24)
- only save relationships for limited restoration to full (schema error)
- only restore relationships if they exist
Commit 2:
- refactored entity snapshot code (for resto extension and conversion)
- refactored applicant code to copy all properties (for resto extension and conversion)
Commit 3:
- fixed people and roles list item spacing
- fixed people and roles code spacing
> 15919 Fixed max expiry date, empty relationships and applicant identifier

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#15969
> 15969 upgrade ApprovalType component

- package-lock.json
- package.json
- src/components/Alteration/AlterationSummary.vue
- src/components/Change/ChangeSummary.vue
- src/components/Conversion/ConversionSummary.vue
- src/components/Restoration/RestorationSummary.vue
- src/components/Restoration/YourCompanySummary.vue
*Issue #:* bcgov/entity#15655
- app version = 4.2.9
- fixed office address formatting on summary pages
- fixed name translation formatting on summary pages
> 15655 Fixed office address and name translation summary formatting

- package-lock.json
- package.json
- tests/unit/LimitedRestorationExtension.spec.ts
- tests/unit/LimitedRestorationToFull.spec.ts
*Issue #:* /bcgov/entity#15080
Unit tests for Extension & Conversion Summary page
> 15080-Unit tests for Extension & Conversion Summary page

- package-lock.json
- package.json
- src/main.ts
*Issue #: [15861](https://github.com/bcgov/entity/issues/15861)
> 15861 update sentry vue sdk

- package-lock.json
- package.json
- src/utils/AxiosInstance.ts
*Issue #:* /bcgov/entity#15241
Minio fix, for when we add it in the future.
> 15241 - Minio fix, for when we add it in the future.

- package-lock.json
- package.json
- src/components/common/YourCompany/BusinessStartDate.vue
- tests/unit/BusinessStartDate.spec.ts
*Issue #:* bcgov/entity#16590
- app version = 4.4.3
- redacted start date blurb for staff
- changed min date to 10 years ago
- removed min start date for staff
- updated a unit test
> 16590 Update min date for firm business start date

- package-lock.json
- package.json
- src/components/SpecialResolution/CreateSpecialResolution.vue
- src/components/SpecialResolution/CreateSpecialResolutionSummary.vue
- src/components/SpecialResolution/HelpSpecialResolution.vue
- src/components/SpecialResolution/Memorandum.vue
- src/components/SpecialResolution/ResolutionEditor.vue
- src/components/SpecialResolution/Rules.vue
- src/components/SpecialResolution/UploadRules.vue
- src/components/common/YourCompany/AssociationType.vue
- src/components/common/YourCompany/EntityName.vue
- src/resources/SpecialResolution/CP.ts
- src/views/SpecialResolution.vue
- tests/unit/Memorandum.spec.ts
- tests/unit/Rules.spec.ts
*Issue #:* /bcgov/entity#15474
https://preview.uxpin.com/53053d7aeb85fb29915f7afa596429aea4f2a964#/pages/162999485/simulate/sitemap
> 15475 - Special Resolution UX fixes

- package-lock.json
- package.json
- src/components/common/YourCompany/BusinessStartDate.vue
- tests/unit/BusinessStartDate.spec.ts
*Issue #:* bcgov/entity#15018
- app version = 4.4.5
- fixed startDateMin
- fixed startDateMax
- added unit tests
> 15018 Fix max business start date

- package-lock.json
- package.json
- src/components/SpecialResolution/Resolution.vue
- src/components/common/YourCompany/AssociationType.vue
*Issue #:* /bcgov/entity#15951
Add in this style of menu for special resolution:
> 15951 - Changes from UX feedback.

- package-lock.json
- package.json
- src/components/Alteration/AlterationSummary.vue
- src/components/Alteration/summary/BusinessType.vue
- src/components/common/YourCompany/ChangeBusinessType.vue
- tests/unit/AlterationSummary.spec.ts
- tests/unit/EntityName.spec.ts
Plus Small dependabot fixes.
*Issue #:* /bcgov/entity#16578
> 16578 - Alteration - Summary changes

- package-lock.json
- package.json
- src/components/Alteration/BcRegEntityDetails.vue
- src/components/Alteration/HelpSectionToggle.vue
- src/components/ViewWrapper.vue
- src/components/common/YourCompany/ChangeBusinessType.vue
- src/components/common/YourCompany/CorrectName/CorrectNameRequest.vue
- src/components/common/YourCompany/EntityName.vue
- src/interfaces/correction-interfaces/correct-name-interface.ts
- src/store/store.ts
- src/views/Alteration.vue
- tests/unit/CorrectNameRequest.spec.ts
*Issue #:*[ /bcgov/entity17186](https://github.com/bcgov/entity/issues/17186)
overall UX check for alteration flow - changing business types
> 17186 - UXA for alterations + Fixes

- package-lock.json
- package.json
- src/components/Alteration/AlterationSummary.vue
- src/components/Alteration/Articles/Articles.vue
- src/components/Alteration/Articles/ResolutionDates.vue
- src/store/store.ts
- tests/unit/ResolutionDates.spec.ts
> 17435 Merge release branch into main

- package-lock.json
- package.json
- src/components/SpecialResolution/ResolutionEditor.vue
*Issue #:* [/bcgov/entity17319](https://github.com/bcgov/entity/issues/17319)
> 17319_fix - Resolution date not passed to signing component

- package-lock.json
- package.json
- src/components/common/YourCompany/FolioInformation.vue
- src/components/common/YourCompany/OfficeAddresses.vue
- src/components/common/YourCompany/RecognitionDateTime.vue
- src/mixins/filing-template-mixin.ts
- src/resources/Correction/CP.ts
- src/store/store.ts
- src/views/Correction/CoopCorrection.vue
- tests/unit/CoopCorrection.spec.ts
*Issue #:* [/bcgov/entity17347](https://github.com/bcgov/entity/issues/17347)
> 17347 - Add additional fields to Correction

- package-lock.json
- package.json
- src/components/SpecialResolution/Resolution.vue
- src/components/SpecialResolution/ResolutionEditor.vue
- src/components/SpecialResolution/SigningParty.vue
*Issue #:* [/bcgov/entity17826](https://github.com/bcgov/entity/issues/17826)
> 17826 - CSR: Special resolution section error handing

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Dockerfile
- devops/cloudbuild-pr.yaml
- package-lock.json
- package.json
- vite.config.js
*Issue #:* bcgov/entity#17593
- app version = 4.7.0
- updated Dockerfile
- changed vitest environment to jsdom
- updated CD script
- updated CI script
- updated PR script
> 17593 Updates for Node 20

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/ListPeopleAndRoles.vue
- src/components/common/PeopleAndRoles/PeopleAndRoles.vue
- src/resources/Correction/CP.ts
- src/store/store.ts
- src/views/Correction/CoopCorrection.vue
- tests/unit/CoopCorrection.spec.ts
- tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#17347
> 17347 - Add in directors for corrections for CP.

- package-lock.json
- package.json
- src/views/Correction/CoopCorrection.vue
*Issue #:* /bcgov/entity#18277
> 18277 - Don't pre select no fee option for co-op correction.

- package-lock.json
- package.json
- src/views/Correction/CoopCorrection.vue
*Issue #:*[ /bcgov/entity18728](https://github.com/bcgov/entity/issues/18728)
> 18728 - COOP Bug: Payment shows up as #3 when it should be #5

- package-lock.json
- package.json
- src/store/store.ts
*Issue #:* /bcgov/entity#18735
> 18735 - Fix rules showing up as being changed, when it's on paper

- package-lock.json
- package.json
- src/components/SpecialResolution/HelpResolution.vue
- src/components/SpecialResolution/InstructionalText.vue
- src/components/SpecialResolution/Resolution.vue
- src/components/SpecialResolution/ResolutionEditor.vue
- src/components/SpecialResolution/SigningParty.vue
- tests/unit/ResolutionEditor.spec.ts
- tests/unit/SigningParty.spec.ts
*Issue #:* [/bcgov/entity18622](https://github.com/bcgov/entity/issues/18622)
> 18622 - Correction - Blank Special Resolution

- package-lock.json
- package.json
- src/components/SpecialResolution/Memorandum.vue
- src/components/SpecialResolution/Resolution.vue
- src/components/SpecialResolution/Rules.vue
- src/store/store.ts
- src/views/Correction/CoopCorrection.vue
- tests/unit/Memorandum.spec.ts
*Issue #:* [/bcgov/entity18495 ](https://github.com/bcgov/entity/issues/18495) [18622](https://github.com/bcgov/entity/issues/18622)
> 18495 - Bug Fix - Show Resolution Section when not Correction Filing

- package-lock.json
- package.json
- src/components/common/YourCompany/AssociationType.vue
*Issue #:* [/bcgov/entity19069](https://github.com/bcgov/entity/issues/19069)
> 19069 - Special Resolution - Validation on blank association type

- .env.example
*Issue #:* /bcgov/entity#19193
updated to use new gcp url
> 19193 updated env legal name

- package-lock.json
- package.json
- src/enums/index.ts
- src/enums/nameType.ts
- src/interfaces/store-interfaces/state-interfaces/business-information-interface.ts
- src/store/store.ts
- tests/unit/EntityInfo.spec.ts
- tests/unit/filing-template-mixin.spec.ts
- tests/unit/state-getters.spec.ts
*Issue #:* /bcgov/entity#20148
- Updated to accommodate alternate name changes in business response
> 20148 Updated to accommodate alternate name changes

- package-lock.json
- package.json
- src/components/common/PeopleAndRoles/OrgPerson.vue
*Issue #:* bcgov/entity#22564
- app version = 4.10.4
- don't show name change checkbox for orgs
> 22564 Added fix for orgs

- package-lock.json
- package.json
- src/components/common/YourCompany/ChangeBusinessType.vue
- src/store/store.ts
- tests/unit/ChangeBusinessType.spec.ts
- tests/unit/utils.ts
*Issue #:* bcgov/entity#22479
- app version = 4.10.5
- convert cont in entity type to regular entity type for v-select, etc
- convert regular entity type to cont in type to prevent equivalent-type changes
- added a unit test
> 22479 Added special handling for cont in entity types

- package-lock.json
- package.json
- src/interfaces/resource-interfaces/resource-interface.ts
- src/resources/Correction/BC.ts
- src/resources/Correction/BEN.ts
- src/resources/Correction/C.ts
- src/resources/Correction/CBEN.ts
- src/resources/Correction/CC.ts
- src/resources/Correction/CCC.ts
- src/resources/Correction/CUL.ts
- src/resources/Correction/ULC.ts
- src/views/Correction/CorpCorrection.vue
*Issue #:* bcgov/entity#22677
- app version = 4.10.6
- replaced @volar-plugins/vetur by volar-service-vetur
- deleted obsolete title and description from resource interface
- deleted title and description (Benefit Company Statement) from resource files (8)
- deleted title and description from HTML template
> 22677 Deleted Benefit Company Statements

- package-lock.json
- package.json
- src/views/Correction/CorpCorrection.vue
*Issue #:* bcgov/entity#23187
- app version = 4.10.9
- fixed incorrect property name
> 23187 Fixed resolution dates not populated in correction

- package-lock.json
- package.json
- src/resources/Alteration/BEN.ts
- src/resources/Alteration/CBEN.ts
*Issue #:* /bcgov/entity#24040
- allow BEN->CC and CBEN->CCC as per updated requirements
> Allow BEN/CBEN to CC/CCC Alteration

- package-lock.json
- package.json
- src/components/common/YourCompany/ChangeBusinessType.vue
*Issue #:* /bcgov/entity#24297
- Fix the bug: when it's a firm correction, can't change the legal type, but the change type section is in editing mode
> Fix - 24297 Fix null original type bug

- package-lock.json
- package.json
- src/components/common/YourCompany/BusinessType.vue
- src/components/common/YourCompany/ChangeBusinessType.vue
*Issue #:* /bcgov/entity#24704
- When the company name error displays, change hint text of input field to "Change company name"
- When the director error displays, change hint text of input field to "Update directors"
- When the company name or director error displays, change styling of input field to red
- When the company name or director error displays, add a red border to the section (invalid style)
> 24704 - Update Type Change Input Section Styling

- package-lock.json
- package.json
*Issue #:* bcgov/entity#26211
- app version = 4.11.20
- updated sbc-common-components (re: KC dependency)
> 26211 Updated sbc-common-components dependency

- package-lock.json
- package.json
*Issue #:* bcgov/entity#26351
- app version = 4.11.19a
- imported latest BaseAddress component
> 26351 imported latest BaseAddress component

- package-lock.json
- package.json
- Update version
- Import latest base-address component
> 26351 - Import Latest Base-address Component

- package-lock.json
- package.json
- tests/unit/ListPeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#26394 
- Update app version
- Import latest BaseAddress component
> 26394 - Import 2.0.42 BaseAddress Component

- package-lock.json
- package.json
- src/utils/AxiosInstance.ts
- vite.config.js
*Issue #:* bcgov/entity#26471
- app version = 4.11.24
- updated app name
- added app name to Vite config
- simplified Vite config
- added App Name to Axios requests
> 26471 added App-Name to request headers

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#25567 
- Import latest ContactInfo 
- Update app version
> 25567 - Import latest ContactInfo component

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#26560 
- Import BaseAddress (2.0.45)
- Update app version
> 26560 - Import BaseAddress with Prioritized Countries

- index.html
- package-lock.json
- package.json
*Issue #:* bcgov/entity#26644
- Update Page Title
- Update App Version
> 26644 - Update Edit-UI Page Title to Manage Business

- package-lock.json
- package.json
- src/mixins/filing-template-mixin.ts
- tests/unit/CoopCorrection.spec.ts
*Issue #:* bcgov/entity#26807
- app version = 4.11.28
- updated party filters for corrections
- updated a unit test
> 26807 Filtered parties for corrections

- package-lock.json
- package.json
- src/interfaces/store-interfaces/state-interfaces/correction-information-interface.ts
- src/mixins/filing-template-mixin.ts
- src/store/store.ts
*Issue #:* /bcgov/entity#26704
Edit UI - Include 'commentOnly' property for Non-correcting corrections
> 26704 Comment Only - Detail Only correction Filing

- package-lock.json
*Issue #:* /bcgov/entity#27519 
- Commit missing package-lock from https://github.com/bcgov/business-edit-ui/pull/628
> 27519 - Add Missing Package-lock

- package-lock.json
- package.json
- src/components/common/YourCompany/CorrectName/CorrectName.vue
- src/components/common/YourCompany/EntityName.vue
- tests/unit/CorrectName.spec.ts
*Issue #:* /bcgov/entity#27630 
> 27630 - Correct Language for Alteration of Company Name

- package-lock.json
- package.json
*Issue #:* bcgov/entity#28833
- app version = 4.12.3
- imported new ShareStructure shared component (ref: https://github.com/bcgov/bcrs-shared-components/pull/283)
> 28833 Imported new share structure component with par value changes

- package-lock.json
- package.json
- src/store/store.ts
*Issue #:* /bcgov/entity#29637 
- This also fixes https://app.zenhub.com/workspaces/entities---olga-65af15f59e89f5043c2911f7/issues/gh/bcgov/entity/29638
> 29637 - Removing Shares Should Display Fee Summary

- package-lock.json
- package.json
- src/components/SpecialResolution/UploadRulesOrMemorandum.vue
- src/components/common/FileUploadPdf.vue
*Issue #:* bcgov/entity#29988
- app version = 4.13.6
- fixed getPresignedUrl issue
> 29988 Fixed issues with uploading coop Rules document

- devops/cloudbuild-pr.yaml
> Update CloudBuild Image

- package-lock.json
- package.json
*Issue #:* /bcgov/entity#24414
> 24414 update fee summary button loading spinner
